### ISSUE TITLE
Favicon needed

### ISSUE THREAD

**Issue by alfonsocrisci** [djavorszky/ddn#100]
Hi guys,

Would you please guys create a favicon for the site? I attach the screenshot of what is displayed in my Favorites toolbar:

![image](https://cloud.githubusercontent.com/assets/7203657/26486437/69111482-41fb-11e7-87f2-ec1d8256f82f.png)

Thanks! :)

**Comment by djavorszky** [comment]
Implemented and pushed to live.

Thanks @alfonsocrisci! :+1:

**Comment by alfonsocrisci** [comment]
Very cool, thanks Dani !
