### ISSUE TITLE
MySQL 5.6: Import failed due to syntax error

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#103]
Database dump is at r2d2/ftp/PFISP-15. It's supposed to be a 5.6 dump:

> "Importing dump failed: could not execute import command: ERROR 1064 (42000) at line 25: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) DEFAULT NULL,\n `modifiedDate` datetime(6) DEFAULT NULL,\n `parentAccountId`' at line 6"

(I tried to import it to my local 5.7 Mysql server (I don't have 5.6) with MySQL Workbench, I think it certainly gets past this point, but after half an hour failed with: ERROR 1114 (HY000) at line 7467: The table 'notificationsetting' is full. So this is not the same problem as in CLoudDB).

**Comment by djavorszky** [comment]
It is indeed a 5.6 dump - to be precise, dumped from a server version 5.6.35.

That said, the error is coming from MySQL itself, complaining about a syntax error, which is strange, as our instance is also version 5.6.

Let me try to import it to my local 5.6

**Comment by djavorszky** [comment]
One of the issues could be the character set of the server perhaps, as the only "utf-8" is the system, everything else is latin1:
```
mysql> show variables like "char%";
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | latin1                     |
| character_set_connection | latin1                     |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | latin1                     |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```

This is in contrast with my own server, where it has passed line 25 already:
```
mysql> show variables like "char%";
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+

```

**Comment by djavorszky** [comment]
Also, import succeeded on my local environment

**Comment by djavorszky** [comment]
Successfully managed to import the mentioned database. Issue may have been fixed in the meantime.
