### ISSUE TITLE
Feature Request - availability of jdbc drivers on site

### ISSUE THREAD

**Issue by alfonsocrisci** [djavorszky/ddn#108]
Hi guys, 

I really like the way CloudDB works so far, thanks ! 

One thing which could make it even more handy would be including a place/link/space/folder/anything you prefer where end users will be able to find and download the appropriate jdbc drivers for the chosen DB type and version.

**Comment by djavorszky** [comment]
Great feature request, thanks! I'd go with providing a link, as hosting (distributing) the drivers may not be possible due to individual licenses.

**Comment by sorin-pop** [comment]
Yes, nice feature request

**Comment by sorin-pop** [comment]
I started doing some research to prepare this feature.

It seems that the JDBC connector 5.1 is the one recommended for the MySQL database versions we use in the cloud: https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-versions.html

Based on this, I think this Maven central repo link should be fine for any MySQL db: http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.43/mysql-connector-java-5.1.43.jar

Regarding how this would look like on the UI, I am thinking of something like this: after you create or import a database, when you see it listed, there woul be an additional option at the Actions button to its right, something like "Download JDBC connector jar". When the user clicks on it, he gets the OS file browser pop-up, and he can navigate to the folder where he wants the jar to be downloaded, and clicks OK. Any thoughts so far?

**Comment by sorin-pop** [comment]
Further research for Oracle JDBC drivers.

We could use the table at http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-faq-090281.html#01_02. Basically: if Oracle 11, ojdbc6.jar, if Oracle 12.1 (the current one in the cloud) ojdbc7.jar, if Oracle 12.2 - ojdbc8.jar.

However, I could not find direct download links for the ojdbc jars. The Oracle maven repo needs registration and on the Oracle download site you need to manually click "Accept License Agreement" before you can download. In these circumstances, perhaps we should just open the http://www.oracle.com/technetwork/database/features/jdbc/index-091264.html link in a new browser tab, and the user can proceed there with choosing the driver he needs and downloading. Or should we keep these jars somewhere on r2d2 and access a direct download link to them, with the file browser pop-up to choose where to save it?

**Comment by djavorszky** [comment]
Hosting the JDBC jars would be a legal mess.. Just to give you an example, Oracle's FAQ page about [distributing jdbc jars](http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-faq-090281.html#02_12) links to their [distribution license](http://www.oracle.com/technetwork/licenses/distribution-license-152002.html) which, after scanning it through, would allow us to distribute it if and only if it's for development/testing, we're not charging anything for it, and quote:

> ... You shall require Your end users to execute an agreement binding them to terms, with respect to the Programs and Programs Documentation ...

And this is only Oracle, we haven't checked any of the others. Instead, I'd link to other sites, deep-link where allowed, download page otherwise.

**Comment by djavorszky** [comment]
Also, I like the idea of the "JDBC" link in the actions dropdown. Another alternative would be a link under the "portal-exts" cards. @alfonsocrisci, what's your take, where would you put it?

**Comment by alfonsocrisci** [comment]
Actions Menu would be a good place.

On the other hand, due to all limitations, I'd be happy even with just having a (plain text) list of matching driver for each DB version. Like a matrix / version scheme, so at least the user knows what version to look for.

**Comment by sorin-pop** [comment]
That's also not a bad idea, yes, Alfonso: something like a new page called 'JDBC driver matrix' or something like that, which would simply show such a table, with external, deep-links directly to jars, or links to download pages (like in the Oracle case above). (This would be easier to implement, as well)

**Comment by sorin-pop** [comment]
For Postgres - provide this link to their JDBC download page:  https://jdbc.postgresql.org/download.html

**Comment by sorin-pop** [comment]
For Microsoft SQl Server: https://www.microsoft.com/en-us/download/details.aspx?id=11774

**Comment by sorin-pop** [comment]
So, I would propose to simply go with the JDBC page approach. So we would need to add a new page with title "JDBC" or "JDBC drivers" or something like that, which would simply list some links to download pages (opened in a new browser tab when clicked). To summarize the info collected above, the list would be this:

MySQL - https://dev.mysql.com/downloads/connector/j/5.1.html
Oracle - http://www.oracle.com/technetwork/database/features/jdbc/index-091264.html
Microsoft SQL Server - https://www.microsoft.com/en-us/download/details.aspx?id=11774
PostgreSQL - https://jdbc.postgresql.org/download.html

I guess @balcsida could add this page in no time, isn't it?

**Comment by djavorszky** [comment]
It's not that easy, as some back-end code is also needed to accept the request and server them, though I think we can work together with @balcsida - me on backend, him on front.

**Comment by sorin-pop** [comment]
Migrated to https://github.com/djavorszky/liferay-support-ee/issues
