### ISSUE TITLE
Client side table sorting/filtering/searching with DataTables

### ISSUE THREAD

**Issue by balcsida** [djavorszky/ddn#113]
Can I assign myself for this?
I'm a big boy, I can handle it.

**Comment by djavorszky** [comment]
By all means, go ahead! I've added you as a collaborator, so you can assign the ticket to yourself.

Quick question, do you want to do this on the front end (via js) or backend (via traditional request-response)?

**Comment by balcsida** [comment]
Only on front end, because: I don't think we have more than 1000 table entries listed and for that low amount of data, even devices with lower HW capabilities have the power to do the sorting/filtering stuff.

**Comment by djavorszky** [comment]
My pleasure! Thanks for suggesting improvements and taking the action to implement them!

If you're doing it on the front end, I was thinking about the same thing for the server browser, do you think you could implement that as well? (if so, I'll open a new issue for it)

**Comment by balcsida** [comment]
Yep, I can implement it for the server browser, too.
Do we have a dev server for testing these kind of things? If not, can you help me to set up one, please?

**Comment by djavorszky** [comment]
No dev server, but pretty easy to set up, provided you have Go installed. If you don't, I can provide you with the current dev binary and other resources. Changing html / javascript does not need server update or restart, so it should be pretty straightforward to test.

Let me know on skype if you have time and I can walk you through it.
