### ISSUE TITLE
Use npm for managing Third Party assets

### ISSUE THREAD

**Issue by balcsida** [djavorszky/ddn#116]
Keeping track of all these packages and making sure they are up to date (or set to the specific versions we need) is tricky. Implementing a package manager makes this easy-peasy lemon squeezy, installing or updating dependencies, like Bootstrap or jQuery is one command away.
Not to mention we can leave these things out from this repo, which makes it more cleaner and easy to follow.

**Comment by djavorszky** [comment]
I'm not sure if there's much merit in this for such a small list of 3rd party dependencies (jquery, bootstrap, font awesome), but I suppose if it did made our lives easier, then that's enough reason to do it.

If you implement it, can you please also update the README.md to reflect the needed steps to make it work?

Thanks!

**Comment by balcsida** [comment]
> I'm not sure if there's much merit in this for such a small list of 3rd party dependencies (jquery, bootstrap, font awesome), but I suppose if it did made our lives easier, then that's enough reason to do it.

This ditches the need to commit every time when jQuery or Bootstrap got updated. That's not related to our code.

> If you implement it, can you please also update the README.md to reflect the needed steps to make it work?

Sure thing!

**Comment by balcsida** [comment]
This gets the highest priority

**Comment by djavorszky** [comment]
Ok, now I understand the power of NPM and why it's great for us. Thanks for suggesting and implementing it!
