### ISSUE TITLE
Unable to Drop MySQL 5.6 db called "forum"

### ISSUE THREAD

**Issue by alfonsocrisci** [djavorszky/ddn#117]
Hi,

I can't drop the MySQL 5.6 db called "forum" from the CloudDB site, it says that the reason is:

> Failed
> connector issue: dropping database failed: dropping database 'forum' failed: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1

Thanks

**Comment by djavorszky** [comment]
Issue arose from accidentally deploying wrong version of connectors - I've deployed the correct versions, adding (and dropping) now works.

**Comment by alfonsocrisci** [comment]
Thanks Dani !
