### ISSUE TITLE
Dump import fails during dump validation

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#127]
Steps to reproduce:

1. Start import with "Browser Server", PFISP-15/khub4.sql into the MySQL 5.7 server.
Result: The process fails at dump validation because it finds more than one create database statements.

"Validating dump failed: more than one \"CREATE DATABASE\" statements found in dump"

Looking at the dump, these statements seem to be actually part of the table contents (probably web content articles), not actual main statements in the dump. So in this case, this validation seems to be too strict, and a showstopper.

**Comment by djavorszky** [comment]
Fixed in #126, haven't had time to push to production yet.

**Comment by sorin-pop** [comment]
Oh, great.
