### ISSUE TITLE
Implement file browser sorting/filtering

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#128]
@balcsida, can I ask you to take care of this as well? :-)

low priority.

**Comment by balcsida** [comment]
Sure thing, I just forgot to do this initially

**Comment by sorin-pop** [comment]
Isn't this already done? I've been seeing such features in Live for some time now, and they are very helpful. So, just wondering, shouldn't this ticket be closed by now?

**Comment by balcsida** [comment]
Hi @sorin-pop,

Nope, it is not implemented yet. Sorting/searching only implemented on the database listing, but not in the file browser.

**Comment by sorin-pop** [comment]
Oh I see, sorry, then I misunderstood the subject of teh ticket a litlle bit.
