### ISSUE TITLE
Allow user to duplicate a dump

### ISSUE THREAD

**Issue by bbsuh** [djavorszky/ddn#134]
Being able to have an action to duplicate (or snapshot/version) a dump would allow users to easily roll back on their test data when their setup requires destructive testing. Examples of destructive testing may include testing that causes failed upgrades, corrupted data, and so on. Having a snapshot point would allow the user to roll back and test on the last known point rather than having to recreate the database, then run through a series of steps to get back to the pre-failed state.

**Comment by sorin-pop** [comment]
Hi Brian, 

Thanks for the involvement! Yep, would be a nice feature, however, I think even currently, it is quite easy to deal with such a scenario, if you just reimport the original dump file you received from the customer(e.g. in a different database name, or in the same, after dropping the existing one, which has been modified during the testing). But I might be wrong, or didn't understand well your idea... Dani?

**Comment by djavorszky** [comment]
Hey Brian,

Yup, great request, I think it'd be pretty neat to be able to do that. Sorin, the steps you mention are basically the ones that could be done automatically with some bookkeeping and convenience functions tied to that, such as the user reverting the database to the snapshot value with a click of a button for example.

The main question is how to implement the whole thing - should we keep a copy of the database as a dump and do some re-import in the background? Should we have a copy of the database already imported, then do some renaming or some such?

At the moment I'm not exactly sure how to approach this feature.

**Comment by sorin-pop** [comment]
Will be partly solved by the export feature. And not sure that we will need more than that. Migrated to https://github.com/djavorszky/liferay-support-ee/issues/6

**Comment by bbsuh** [comment]
Thanks!
