### ISSUE TITLE
MySQL case sensitive/insensitive issue

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#136]
It seems that when we start the portal on a case sensitive MySQl server, and the imported table names start with small letters, the portal will recreate all tables, with capital letter, ending up in all tables existing two time: one with small letter, containning the imported customer data, and one with capital letter, created by the portal at startup (and being empty or containing just the default data that Liferay generates at startup). This results in the UI using the capital letter tables, and thus looking as if you are running on a clean database, instead of seeing customer's data.

**Comment by alfonsocrisci** [comment]
Could be related:

https://dba.stackexchange.com/questions/59407/how-to-make-mysql-table-name-case-insensitive-in-ubuntu

https://stackoverflow.com/questions/6134006/are-table-names-in-mysql-case-sensitive

https://issues.liferay.com/browse/LPS-33190

**Comment by djavorszky** [comment]
Thanks @alfonsocrisci!

I've added `lower_case_table_names=1` to all mysql servers and have restarted each.

@sorin-pop, can you please try again?

**Comment by sorin-pop** [comment]
This seems to be OK now, based on my early observations. I think it's fixed. We'll reopen it if not.

Thanks a bunch @alfonsocrisci for the suggestion, and @djavorszky for quickly reacting and fixing it.
