### ISSUE TITLE
No hints when DB name is wrong due to prepended space

### ISSUE THREAD

**Issue by alfonsocrisci** [djavorszky/ddn#137]
Hi team,

Please feel free to change this issue to enhancement, I did not find a way to do this by myself.

Steps:

1) Go on http://cloud-db.liferay.int/createdb
2) Select any DB Engine
3) In the Database Name field put a space, then start to type the DB name

**Actual behavior:** A red cross indicating an error will appear on the right side of the field. This is good, but there will not be any visual indication saying why the field validation failed, not in the interface, not even when hovering the mouse on the cross.

![image](https://user-images.githubusercontent.com/7203657/27679708-c4e1b2d4-5cb9-11e7-9caf-5ef7782f6d26.png)

**Expected behavior:** There should be a visual indication/tooltip saying that db names cannot contain spaces or the field should trim those, I leave this decision to you guys. Specific business use-case is that a user may enter the value on that field just by copying the text with space from somewhere else

Thanks !

**Comment by djavorszky** [comment]
Thanks for the thorough report Alfonso! You're right, we should have something there. For now, I'll label this as an enhancement and ask @balcsida for his input on this, as he's a bit more knowledgeable on this than I am.

**Comment by balcsida** [comment]
Thank you for the feedback, @alfonsocrisci!
I will implement a basic error hinting-something-awesome for fixing this.
