### ISSUE TITLE
Failed imports should be removed within two days by default

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#139]
IMHO... what do you think @sorin-pop?

**Comment by sorin-pop** [comment]
I think it's a great idea! I was thinking one of these days about how pretty annoying is the fact that the failed imports are flooding the list, but didn't have the brains to think of some solution. And I think this would be the ideal solution, Dani.

**Comment by djavorszky** [comment]
Implemented as of a813bf723d8d76d995a119de71503942b421e2ae
