### ISSUE TITLE
Can't drop database gobsmalyalt2_cluster

### ISSUE THREAD

**Issue by alfonsocrisci** [djavorszky/ddn#140]
Hi Guys, 

I'm unable to drop the DB gobsmalyalt2_cluster, both from the site and through MySQL Workbench:

```
Could not Drop Object
("Error dropping database (can't rmdir './gobsmalyalt2_cluster', errno: 39)", 1010)

DROP DATABASE `gobsmalyalt2_cluster`
```

Thanks !

**Comment by djavorszky** [comment]
Thanks @alfonsocrisci for the report!

Seems to be a "regression" from setting the lower_case_table_names to 1: https://stackoverflow.com/a/22300803

We'll be probably running into this issue for a couple of databases. Which version of mysql is this?

**Comment by alfonsocrisci** [comment]
This one in on MySQL 5.7

**Comment by alfonsocrisci** [comment]
I assume this happens as the DB was created before the change you mentioned and won't happen on new DBs. If so, no problems for me, you may "hard drop" manually this DB, it will be fine.

**Comment by djavorszky** [comment]
Yup, that's what I think as well.. only already imported databases are affected that have non-lowercase letters in table names.

**Comment by djavorszky** [comment]
Dropped, thanks!
