### ISSUE TITLE
Possible issue regarding the "Create database" API endpoint

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#141]
I'm trying to make use of this API from LiferayUP, and after reading the API documentation for creating a database, it seems to me that it is lacking an important input parameter: the connector (short) name. In other words, I can tell CloudDB what to be the name of the new database, and for which user should it be created, but not in which database server to create them: MySQL 5.5, or 5.7, or the Oracle one?

I would need an API call to which I can tell which connector should be used for creating the database, same as on the UI we have a drop-down list for that. The input should be one of the values returned by the /api/list API call: currently mysql-55, mysql-56, mysql-57, oracle-12

Or am I missing, misundersanding something, @djavorszky ?

**Comment by djavorszky** [comment]
Can you link to the documentation or just share it with me? Maybe it's just a wording issue at one point or another - the "connector_identifier" is used to get the connector itself, which is saved with the shortname.

That said, we'll be refactoring the api endpoints - just shared a document with you. That's a proposal still, not yet implemented

**Comment by sorin-pop** [comment]
Dani, it's in the Wiki/API Reference :)

Looking forward to correct instructions on how I should invoke the create-database API endpoint.

**Comment by sorin-pop** [comment]
Hi Dani,

I have commented on the draft you sent. What I would need for the create-database API is not only to be able to provide the connector, but it should also return the portal-ext JDBC connection strings when successful (just like on the UI).

Do you think I can get such an API soon? I'd really like to make some progress with the LiferayUP integration.

**Comment by djavorszky** [comment]
As discussed on another venue, I'm closing this issue - create database api already exists (/api/create), portalext api will not be added, instead, I'll be adding the query-for-connector api on #143
