### ISSUE TITLE
Containerize DDN

### ISSUE THREAD

**Issue by balcsida** [djavorszky/ddn#144]
As we discused with @djavorszky, it would be awesome, if we could create a DDN Docker container that includes all the necessary thing for running the DDN server+web.
Possible considerations:

- Use more lightweight DB for the backend (I suggest SQLite)

**Comment by djavorszky** [comment]
If we go with sqlite3, there's a driver we can use @ https://github.com/mattn/go-sqlite3.

We'd also need an image which we can use as a base for ourselves.. any suggestions @balcsida?

**Comment by djavorszky** [comment]
Going to go with building a container based on the alpine one, installing sqlite3 and adding the server inside.

Stuff to do:
- [ ] Implement sqlite connection (#169)
- [ ] Create dockerfile
- [ ] Create deploy script

**Comment by djavorszky** [comment]
Completed as of 2c76c32d418d267c78e8c5e0e9da23bf6508cca9

See https://hub.docker.com/r/djavorszky/ddn/
