### ISSUE TITLE
Possible inconsistecy between UI and API Oracle database creation

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#145]
When we create an Oracle db from the UI, we ignore the database name field. The database (actually Oracle schema) name will be what we give as user name. 

connector/oracle.go:

```
func (db *oracle) CreateDatabase(dbRequest model.DBRequest) error {

	err := db.Alive()
	if err != nil {
		return fmt.Errorf("alive check failed: %s", err.Error())
	}

	args := []string{"-L", "-S", fmt.Sprintf("%s/%s", conf.User, conf.Password), "@./sql/oracle/create_schema.sql", dbRequest.Username, dbRequest.Password, conf.Tablespace}
```
However, the create API seems to not work according to this, and it creates the database record in CloudDB's metadata database with what you gave for parameter database_name.

curl -X POST -d "{\"requester_email\":\"sorin.pop@liferay.com\", \"connector_identifier\":\"mysql-55\", \"database_name\":\"sorin_api_test\", \"Username\":\"sorin\", \"Password\":\"test\"}" cloud-db.liferay.int/api/create

will create correctly an Oracle schema named sorin, but also a metadata record for it saying the database name is  sorin_api_test, which is not correct, it should be sorin. The UI will show a database with name sorin_api_test, and if you click on actions/portal-exts you get:

jdbc.default.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.default.url=jdbc:oracle:thin:@192.168.211.213:1521:orcl
jdbc.default.username=sorin
jdbc.default.password=test

which is correct.

If I leave empty the database_name in the API call, it will generate some random database name in the metadata db.

I noticed this while developing and testing the API for LiferayUP. Dani, can you correct it, or should I look into it?

**Comment by sorin-pop** [comment]
I had a look into it, as Dani is on holiday.

I think the UI version is handled in server/handlers.go, and this bit in CreateAction(), doPrepImport(),importAction():

if dbname == "" && dbuser != "" {
		dbname = dbuser
	}

is responsible for handling this kind of situation.

The API version seems to be in server/api.go/apiCreate method, the medata database record is created with values:

dbe := database.Entry{
		DBName:        req.DatabaseName,
		DBUser:        req.Username,
		DBPass:        req.Password,

but there's no check before to see if req.DatabaseName is empty. And ensureValues(&req.DatabaseName,... will give it some random value if it's empty.

So I guess one solution would be to put a similar check there, before ensureValues().

Perhaps I'll send a pull request.

**Comment by sorin-pop** [comment]
Pull request: https://github.com/djavorszky/ddn/pull/146

**Comment by djavorszky** [comment]
Merged, thx!

**Comment by sorin-pop** [comment]
Hi Dani,

Could you please let me know when this will be live?

**Comment by djavorszky** [comment]
I'll try to do a push to prod later today, as I'll be in home office tomorrow and the day after.
