### ISSUE TITLE
api/create sometimes returns "status", sometimes "Status"

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#152]
It seem that when the API call fails, the JSON string contains "Status", when successful: "status"

```
curl -X POST -d "{\"requester_email\":\"sorin.pop@liferay.com\", \"connector_identifier\":\"mysql-55\", \"database_name\":\"sorin_api_test\", \"Username\":\"sorin\", \"Password\":\"test\"}" cloud-db.liferay.int/api/create
{"id":356,"vendor":"mysql","dbname":"sorin_api_test","dbuser":"sorin","dbpass":"test","sid":"","dumplocation":"","createdate":"2017-07-25T21:01:53.387397708+02:00","expirydate":"2017-08-25T21:01:53.387397859+02:00","creator":"sorin.pop@liferay.com","connector":"mysql-55","dbaddress":"cloud-db.liferay.int","dbport":"3306","status":100,"message":"","public":0}
```

Run the same again:

```
curl -X POST -d "{\"requester_email\":\"sorin.pop@liferay.com\", \"connector_identifier\":\"mysql-55\", \"database_name\":\"sorin_api_test\", \"Username\":\"sorin\", \"Password\":\"test\"}" cloud-db.liferay.int/api/create
{"Status":305,"Message":"creating database failed: sending json message failed: got non-200 response '500' and message: {\"Status\":305,\"Message\":\"creating database failed: database 'sorin_api_test' already exists\"}"}
```
...which doesn't seem consistent, and breaks my code that calls the API.

I had a look at server/api.go and I only see Status lines in inet.SendResponse parts, so I'm not sure where the problem lies. Dani, can you help?

In my LiferayUP code I check for "status", as that what I have seen as returned when a successful call is completed:

```
JSONObject jsonResponse = new JSONObject(jsonResponseString);
int status = jsonResponse.getInt("status");
```

An now, that I ran into a failed call, this fails with:

21:13:42.986 [Performer] ERROR com.liferay.up.util.CloudDBUtil - JSONObject["status"] not found.
org.json.JSONException: JSONObject["status"] not found.

because it seems to return "Status" with capital s. So I would need, ideally, a consistent JSON response from this point of view: that status returned should always be named the same. Do you think the problem is in ClouDB's API, or perhaps I am doing something wrong?

**Comment by djavorszky** [comment]
Yup, totally justified, JSON keys should be consistent and lowercase. Just pushed a fix to master, though I wouldn't necessarily bring down cloud-db just to apply this fix.

**Comment by sorin-pop** [comment]
Thanks @djavorszky . Could you please let me know when you will apply this fix in live? Thanks.

**Comment by djavorszky** [comment]
Given my current workload and other tasks, the earliest I can say is sometime next week.

Can you test with a local installation until then?

**Comment by sorin-pop** [comment]
Yep, that's fine, thanks.

On Wed, Jul 26, 2017 at 10:14 AM, Daniel Javorszky <notifications@github.com
