### ISSUE TITLE
Oracle server: handle the automatic release of disk space when users (schemas) are dropped

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#154]
We recently ran into https://github.com/djavorszky/ddn/issues/153, which is due to the fact that in Oracle, the data files associated with a tablespace, once they have been automatically extended according to the needs, are not automatically "contracted", shrinked back when we drop a user. The space is logically released within the tablespace (so new dump imports will have where to store the data), but the datafiles of the tablespace hold on to that space on the disk. In case these datafiles have been extended as far as to leave no free space on the VM's disk, every new CloudDB import operation will fail almost instantly, since it will not be able to process its very first step: the copying of the dump file to the VM.

And (as my current research related to solving https://github.com/djavorszky/ddn/issues/153 showed)
, it is not an easy task to shrink back such datafiles from such a situation.

Therefore we recognized that for the future we'll need some kind of mechanism which prevents running into this problem after a while, which would prevent the datafiles growing until there is no more space left on the device. (and simply dropping old users, which CoudDB does automatically do currently, does actually not have any disk-space freeing impact).

@djavorszky was thinking of some weekly job that would do this reorganization, reclaiming of disk space. But as far as I could see now while working on https://github.com/djavorszky/ddn/issues/153, it won't be easy to write such a script (if at all possible).

I just had a discussion with Jándi Tibi, and he came up with what seems as a simple and after all quite elegant solution for this: we should just simply put every user in its own tablespace. For every created user we should also create a tablespace and assign that user to that tablespace. And when we drop that user, we also drop that tablespace together with its datafile:

"DROP TABLESPACE xxx INCLUDING CONTENTS AND DATAFILES"

And this would ensure that the disk space is automatically reclaimed.

(Creating a tablespace for each user doesn't seem like a very elegant and usual thing to do for me, but I still like the idea, and it is very elegant at the part when we are dropping the user: it automatically releases the disk space that was occupied by its schema objects. And so we don't have to put together some very complicated table reorganization script.)

What do you guys think?
@djavorszky @giros @janditibi @balcsida

**Comment by djavorszky** [comment]
I'm fine with this change if reducing the size of the tablespace is very problematic. Actually, from an application perspective, there's no strong reason for or against either of the approaches (all dbs to one tablespace vs to their own). Whether it's elegant or not - I consider the Oracle server (along with all the other ones) as a developer database which have minimal connection to production environments, so their main purpose is to work without issues.

There's two places where we'd need to change the logic: In the import and drop scripts, which doesn't seem to be too big of a change, and in the connector's logic to provide a tablespace name to the import/drop scripts.

I wouldn't necessarily want end users to be able to specify tablespace names, because in the end it's not something that matters for them. Instead, we could simply generate a name based on the importing user or database name or some other factor, making sure they are unique.

All in all, this doesn't seem too big of a change, at least from first glance, and actually may be easier than writing a weekly/monthly job of truncating the mono-tablespace.

Of course, this still leaves us with handling the current situation - I'd suggest exporting the databases that users still need, drop current tablespace including contents and datafiles, then reimport them through the UI.

Just my $0.02

**Comment by sorin-pop** [comment]
> I wouldn't necessarily want end users to be able to specify tablespace names, because in the end it's not something that matters for them. Instead, we could simply generate a name based on the importing user or database name or some other factor, making sure they are unique.

Exactly. This would all be done in the background. I was thinking that actually the tablespace name could be exactly the same as the user (schema) name, I don't think this would cause any problems.

> All in all, this doesn't seem too big of a change, at least from first glance, and actually may be easier than writing a weekly/monthly job of truncating the mono-tablespace.
Yep, that's what I thought as well.

> Of course, this still leaves us with handling the current situation - I'd suggest exporting the databases that users still need, drop current tablespace including contents and datafiles, then reimport them through the UI.
This sounds like a good and workable idea. Perhaps we should first quickly implement the every-user-with its-own-tablespace solution, and then import them back (so that they are imported back already according to the new system), right, Dani?

Regarding the every-user-with its-own-tablespace, currently am envisioning one possible (although probably rare) problem. Let's say I am planning to create each tablespace with one datafile (seems the most straightforward and simple thing to do). Practice showed (and @giros confirmed) that even if I create a datafile with max size UNLIMITED, that "unlimited" actually means about 30-32 GB for some reason. So in this case, if somebody would import a very very large dump that would need to extend the tablespace's only datafile to more than 30-32 GB, it will fail (or hang). Considerations:
- I don't know how often this would be the case, if at all, to have such a large dump (actually I think it can happen, so I wouldn't ignore this scenario)
- the only way to avoid this, as I see now, is to create one or two additional datafiles (with a small initial size) for each user's tablespace (making sure that if the first one reaches 30GB, the second one is used automatically for the further data importing, and so on. The current mono-tablespace also has 3 datafiles, actually, after we realized that it needs them.)
- and there would be no problem at dropping the tablespace from thsi point of view, as the INCLUDING CONTENTS AND DATAFILES clause speaks for itself (it will automatically delete all 3 datafiles, no matter which ones and to wehich degree the were actually used) 

Thoughts on this?

**Comment by djavorszky** [comment]
> This sounds like a good and workable idea. Perhaps we should first quickly implement the every-user-with its-own-tablespace solution, and then import them back (so that they are imported back already according to the new system), right, Dani?

Yeah, that's what I meant - reimport them once we implemented the change.

Is there any downside to automatically creating the tablespace with 2+ datafiles? I guess minimal initial size for the file, but that must be minuscule compared to the actual size it would grow to if it was needed.

If we want to make it extra clever, we could decide how many datafiles to create based on the size of the dump file.. I wouldn't do this though, as the cost of creating additional datafiles that may not be used are very small compared to the added complexity and potential bugs we would be adding.

I'd like to propose to go with the following:
1. Tablespace-per-import, or per user, or whatever makes sense for Oracle databases
2. Two datafiles.

I think the next step is implementation - @sorin-pop, do you think you can take care of this?

Thanks,
Dani

**Comment by sorin-pop** [comment]
> Is there any downside to automatically creating the tablespace with 2+ datafiles? I guess minimal initial size for the file, but that must be minuscule compared to the actual size it would grow to if it was needed.
Yes, the downside would be that the extra datafiles (which most of the time wouldn't even be used) would unnecessarily occupy some disk space according to their initial size. But if we define this initial size to something fairly small, I don't think this downside would be relevant.

> If we want to make it extra clever, we could decide how many datafiles to create based on the size of the dump file.. I wouldn't do this though, as the cost of creating additional datafiles that may not be used are very small compared to the added complexity and potential bugs we would be adding.

Yes, I was also thinking about something like this and I looked around, but it seems there's no very clear and exact rule of thumb to determine the amount of needed disk space from the size of the dump file. What seems to be sure is that you will need at least the size of the dump file as free disk space in the tablespace's datafiles. But I agree with you that we should not go this way, for now. I think the gameplan you proposed is good and shoud be fine, and I should also be able to implement it quite quickly theoretically. So I will get on to it today.

**Comment by sorin-pop** [comment]
Pull request: https://github.com/djavorszky/ddn/pull/156

I also did basic testing for database creation, dropping and import and it worked fine.

Dani, please let me know the next steps we should take. (collect the needed oracle databases and export them, and after that install this change, and import the dumps?)

**Comment by djavorszky** [comment]
Thanks @sorin-pop!

Yes, the next steps are pretty much what you wrote:
1. Update connector at Oracle
2. Gather all oracle databases that are still active 
3. Export and reimport the ones that are still needed
4. Drop everything else

Let's talk on Skype about these steps

**Comment by sorin-pop** [comment]
The steps were done and changes were installed on the Oracle connector. I am closing this ticket.
