### ISSUE TITLE
Drop/Create DB with same name and credentials

### ISSUE THREAD

**Issue by alfonsocrisci** [djavorszky/ddn#155]
Hello Team,

I'm suggesting this feature: dropping and recreating a DB with same name and credentials in one action. This would allow having a fresh DB where to perform a new test with one click, without going through multiple actions and without modifying the portal-ext.properties.

Thanks for your time and consideration !

**Comment by djavorszky** [comment]
I like this idea, and it doesn't look too hard to implement, as we already have the logic to drop and create databases.

I'd say we could add a button to the "Actions" sections, say, "Recreate", that would show a confirmation to the user, informing them that all data will be lost (and if it was an import, the dump will not be reimported).

If user says "ok cool", then we simply drop the database then create it with the very same information in the background.

All of these have examples already, so should be pretty easy to implement.

**Comment by djavorszky** [comment]
:+1: Implemented as of abcdeba - already on live as well
