### ISSUE TITLE
Cloud DB UI: set of columns for private and public databases is not the same

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#157]
The private section has one additional column (Vendor). Is this intended for some reason?

(if not, I guess we could remove that column, as that information is pretty obvious from the Connector column anyway, so it seems somewhat superfluous)

![capture](https://user-images.githubusercontent.com/7113037/28868479-dfd421f0-7779-11e7-9fda-9a4aff05402b.PNG)

**Comment by djavorszky** [comment]
The public has an additional too: Owner.

The vendor was removed from the public because the Owner was added, and the columns got too small. You're right though, Vendor isn't really needed, as the name of the connector implies it.

Feel free to remove it and send a pull :-)

**Comment by sorin-pop** [comment]
Here is the pull request: https://github.com/djavorszky/ddn/pull/159

**Comment by djavorszky** [comment]
Merged, thx!
