### ISSUE TITLE
Provide a web based database administration tool

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#158]
Here's an idea:

We could provide a textbox for users to execute SQL queries with the users they created on databases they have permissions for.

Why? Sometimes we need to run some queries on the databases which we have created and imported, but our local environments may not have the necessary tools to connect to the remote databases to execute such queries.

For example, most of us have MySQL clients (and MySQL workbench) installed, but no Oracle, MSSQL or Postgres editors / clients with which we could execute the queries.

The actual usecase that gave birth to this idea was me successfully importing a database, but before continuing with using it, I have to actually run two queries on it.

This wouldn't be trivial, as we'd have to make sure that only the owners of the databases can execute queries on their dbs (even for Public ones?) (disregard lack of authentication), and also think about how to return the resultsets from the databases, what to do in case of errors, etc.

@sorin-pop, @balcsida,  @alfonsocrisci what do you guys think?
Dani

**Comment by sorin-pop** [comment]
Hi guys,

I think this would be a tremendous effort indeed. We would actually "reinvent the wheel" and implement our own "workbench" from scratch. I think it will be very complicated and time and resource consuming to implement such a thing, compared to the fact that the initial problem which sparked the idea is not such a big problem, I would say. For MySQL indeed most of us already have the MYSQL workbench. Cool.

Now let's take Oracle. I am using SQL Developer: easy and fast to install and use, and we have one already on r2d2/install. But if you want the latest version, I'm pretty sure it's for free out there on the web.

For MS SQL Server (by the way, we still need to enable this in the cloud), there's TOAD for SQL Server, for free (I think I already used it without any issues on my previous work PC). For example: https://www.toadworld.com/m/freeware/550

For Postgres: It seems there a TOAD (Quest Software) freeware for that as well --> https://www.toadworld.com/products/toad-data-modeler/b/weblog/archive/2011/08/01/freeware-database-modeling-tool-for-postgresql-9-0
But I'm sure if you search a bit, you can find other tools as well.

So, it seems that for all major database vendors it is pretty simple to find and install some client for connecting to a remote database of that type and then run SQL queries on it and so on. True, you would need pretty much a different tool for each one, but you only need to install them once and know which one to use for which type of database. I'm quite fine with this, frankly.

Of course, a unified interface within the Cloud DB UI for this same purpose would be nice (and elegant) thing to have, but I think it would be a very very big development task (and will only be a more primitive, and buggy, version of what all these professional tools already know).

Nevertheless, if you still decide to go for it, I can take my share in the development (I guess).

Just my 2 cents (or how do they say it)

**Comment by djavorszky** [comment]
I agree with you in that we should not reinvent the wheel, and in fact, we shouldn't.

What I'm suggesting is basically allowing users to forward queries to the connectors for execution and returning the results, be that rows, a statement that it was understood (e.g. updating rows) or an error message.

My problem with installing clients locally is that we already support 4 database vendors: MySQL, Oracle, Postgres and MSSQL (true, only 2 vendors are currently active). If we add others, like DB2 or Sybase, we're looking at 6 clients that we may only need once.

**Comment by balcsida** [comment]
We don't need to reinvent the wheel as there are existing tools available like phpMyAdmin or Adminer.
We simply make a button to drop the user to a DB admin tool and he/she can do anything he/she wants.

**Comment by djavorszky** [comment]
Thanks for the input @balcsida! We've already discussed this in person that we'll be going forward with this method, hosting Adminer or phpMyAdmin somewhere and adding a button somewhere on the UI that'll take the user there so that they'll be able to manage their databases.

**Comment by sorin-pop** [comment]
Migrated to https://github.com/djavorszky/liferay-support-ee/issues
