### ISSUE TITLE
connector: Implement GetDumpInfo function for Oracle

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#16]
Input:
- dump file location (it will probably be necessary to be somewhere on the machine that runs the Oracle database)
- dump file name

Output:
- dumpType - data pump or classical
If the dump file was generated with data pump (expdp), the function will also return further relevant (not empty) information:
- sourceDBVersion - from what Oracle version was the export generated
- dumpEncrypted - if the dump is encrypted (possible since Oracle 11g). It rarely happens that we get encrypted dumps from customers, but it's nevertheless good to be prepared, and if that's the case, CloudDB UI will need to ask user for the decryption password he received from customer
- exportedSchemas  - what users/schemas did the customer export in the dump (needed for remapping during import)
- exportedTablespaces - to which tablespaces do the exported schemas belong (needed for remapping during import to our tablespace)

**Comment by djavorszky** [comment]
Couple of notes:
* The import method of the database gets a local file system path, see https://github.com/djavorszky/ddnc/blob/master/process.go#L11-L23, so download already happens - though the file is discarded once the import finishes.
* The output should be a struct, simply called `Dump` perhaps? Or `DumpInfo`?
* I think if we go with the struct, we can shorten the variable names to `Type`, `Version`, `Encrypted`, `Schemas` and `Tablespaces`

What do you think? 
Dani

**Comment by sorin-pop** [comment]
Yes, I agree. I did not start working on this yet, as I realized that changes from my previous pull request are needed (e.g. RunCommand function). So let's clarify and finalize that first.
