### ISSUE TITLE
Import fails dirtily if archive contains files in a folder

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#160]
For example:
dump.zip contains:
dumpFolder/dumpFile.sql

Error message:
```
Extracting file failed: extracting zip file failed: opening destination file failed: open vmware/: The filename, directory name, or volume label syntax is incorrect.
```

**Comment by djavorszky** [comment]
In my opinion, the expected result should be: If only a folder is present, step into it, then continue with import logic.

Current restrictions apply:
1. Fail if multiple files/folders
2. Start import if only one file present

**Comment by sorin-pop** [comment]
Migrated to https://github.com/djavorszky/liferay-support-ee/issues
