### ISSUE TITLE
Oracle import: implement possibility to handle multiple dump files

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#161]
Sometimes, quite rarely, the customer is doing the export in multiple dump files, which have to be handled together at import time. But currently clouddb can only handle one dump file. You can only provide one on the UI, and the import SQL scripts are also assuming that you pass to them one dump file.

I will soon start working to see if we could somehow add the handling of multiple dump files as well.

**Comment by sorin-pop** [comment]
I have implemented  this at the Oracle level, in the stored procedure which does the import. By the way, I haven't added its code to the repo so far (because it doesn't have to sit there as a file somewhere, it just needs to be run once, or when we change something in it, and then it's there in the database, as a db object), but probably it should be tracked here in the repo, so I am filling this gap now: https://github.com/djavorszky/ddn/pull/162

The procedure now can also receive a list of dump files (only the names) as its second parameter, separated by commas (and no spaces). E.g. "file1.dmp, file2.dmp,file3.dmp"

This would mean that in the Go connector layer, oracle.go/ImportDatabase function:

`// Start the import
	args := []string{"-L", "-S", fmt.Sprintf("%s/%s", conf.User, conf.Password), "@./sql/oracle/import_dump.sql", dumpDir, fileName, dbRequest.Username, dbRequest.Password, conf.DatafileDir}`

we should make sure that we modify the handling the fileName parameter. If the user selected several dump files, or (I guess) selected one zip containing several dump files, then we should be able to pass here the list of the dum file names separated with commas.

And of course also the server UI layer needs to be updated to be able to handle the selection of multiple files, or take into account all the non-log files from any packed file we select.

@djavorszky Do you think you can take care of these other layers? You are probably the best person to handle this there.

**Comment by djavorszky** [comment]
Hey Sorin,

Thanks for implementing this! If I understand you well, no changes are required in how the filenames are passed to your import script, right? As long as the "fileName" is either the name of one file, or is a comma-only-delimited list of names, then the procedure will work.

As for running it once to add the stored procedure to the database: I'd like to automate that process via the connector. Do you think we could try to drop/add it at connector startup and handle any issues gracefully? This way, we can be sure that if we need to update the procedure, the change takes effect at connector startup. Also makes our life easier if someone else wants to set up cloud db for themselves - less things to do manually.

I'll open a new ticket for making it possible to actually use the new procedure.

**Comment by sorin-pop** [comment]
> If I understand you well, no changes are required in how the filenames are passed to your import script, right? As long as the "fileName" is either the name of one file, or is a comma-only-delimited list of names, then the procedure will work.
Yes, exactly.

> As for running it once to add the stored procedure to the database: I'd like to automate that process via the connector. Do you think we could try to drop/add it at connector startup and handle any issues gracefully? This way, we can be sure that if we need to update the procedure, the change takes effect at connector startup. Also makes our life easier if someone else wants to set up cloud db for themselves - less things to do manually.

Not a bad idea. Basically at connector startup, we would just need to call the /sql/oracle/import_procedure.sql script via sqlplus (connected as system) in pretty much the same way we call create_schema.sql, ,drop_schema.sql and import_dump.sql (actually it's easier, as we don't even have to pass parameters to this one). The file actually contains CREATE OR REPLACE PROCEDURE command, so you can think of it as  a drop/recreate. Basically if the stored procedure doesn't exist, it will create and compile it. If it already exists, it will recompile it, replace it with the actual body code in the file.

**Comment by djavorszky** [comment]
Awesome! I've opened #163 to implement the UI / API changes.

Do you want to add the call to the import_procedure.sql at connector startup (if oracle), or want me to take care of it?

**Comment by sorin-pop** [comment]
I'll try to handle that: https://github.com/djavorszky/ddn/issues/164

So should we close this ticket now?

**Comment by djavorszky** [comment]
Yup, let's close this and continue on 164.
