### ISSUE TITLE
Run the import_procedure.sql when the Oracle connector starts up

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#164]
So that the strored procedure is created if non-existent, or refreshed (if we made some modification in its code)

**Comment by sorin-pop** [comment]
Pull request: https://github.com/djavorszky/ddn/pull/167

**Comment by sorin-pop** [comment]
Still, if we modify something in any sql script file from under sql/oracle, we need to copy it manually. I was thinking that perhaps we could automate that as well. E.g. the connector, when it starts, checks its local sql scripts and the one in the remote github repo (branch master, I guess), and compares them. If it sees that some of them are newer in the repo, it informs the user and prompts him if he wants the version from the github to be copied over and override the current script(s). But that should be the subject of a different ticket.

**Comment by sorin-pop** [comment]
I am closing this, As it was implemented and modified after review. The pull problem with the con.conf file, I guess can be handled on your side by adding to it that comment:

# For Oracle, it is recommended that the db-username is the system user
# Also, the below grants are needed from SYS in order for the Oracle
# import stored procedure to compile successfully:

**Comment by djavorszky** [comment]
Thanks Sorin! Added the comments to the con.conf: c3118e67e5ed6d61bee29431fb808c6e1f34fcfa
