### ISSUE TITLE
Import database failed due to dump trying to create another database

### ISSUE THREAD

**Issue by sebastian-madaras** [djavorszky/ddn#165]
Hi All, 

I encountered the following issue:

1.) Import database from '/r2d2/tmp/clouddb/mysql_55_long_running_import.sql'. The file should be imported with MySQL 5.6 database type:

I got the following Email:

Import database failed

Your request to import a(n) "mysql" database named "--obfuscated--" has failed with the following message:

"Importing dump failed: could not execute import command: Warning: Using a password on the command line interface can be insecure.\nERROR 1044 (42000) at line 23: Access denied for user 'sebi'@'%' to database '--obfuscated--'"

Please let me know if you need any additional info.

Best regards and thank you.
Sebi

**Comment by djavorszky** [comment]
Same as #151, will handle it there.
