### ISSUE TITLE
Public database import (into mysql 5.5) hanging?

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#166]
It was started yesterday afternoon and the UI still shows Importing...

Dani, could you please have a look what is going on in the background?

Thanks

**Comment by djavorszky** [comment]
According to the output of "show processlist" command, the import is still running:

| 4780 | sebike86 | localhost       | --obfuscated-- | Query   |    1 | update | INSERT INTO `--obfuscated--` VALUES ('--obfuscated--',--obfuscated--,--obfuscated--,--obfuscated--,' |

**Comment by sorin-pop** [comment]
Thanks, we'll wait then.
