### ISSUE TITLE
New API needed to get a connector's parameters, necessary to be used in portal-ext JDBC connection settings

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#174]
Input parameter: connector_identifier (just as the one for /api/create)

Output:

dbaddress (database host)

dbport (databse port)

sid (populated only in case of Oracle)

We currently need this API in order to implement the "existing database" feature in LiferayUP, where you know you already have an imported dump in CloudDB (and you know its type and name), and want to set up a bundle that points to that db. See https://github.com/vilmospapp/liferay-support-ee/issues/236

@djavorszky , you wanna do this, or should I give it a try?

**Comment by djavorszky** [comment]
Already in:

/api/connectors/shortname

e.g. api/connectors/mysql-55

**Comment by sorin-pop** [comment]
Wow, great!
