### ISSUE TITLE
Import chooser UI is inconsistent, not updated to BS4 beta

### ISSUE THREAD

**Issue by balcsida** [djavorszky/ddn#185]
Turn this:

![image](https://user-images.githubusercontent.com/1768446/29620403-20e86f70-881e-11e7-86a8-cf9de300dd02.png)

into this:
![image](https://user-images.githubusercontent.com/1768446/29620389-17772fbc-881e-11e7-8904-91113b5c63db.png)

**Comment by djavorszky** [comment]
Enhanced with 4effbcf, thanks!
