### ISSUE TITLE
connector: Implement SQL Server support

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#19]

**Comment by sorin-pop** [comment]
I can work on this after Oracle is done and tested thoroughly. I already have some scripts courtesy of Borkuti péter. 

But basically, the expectation now is for Oracle to work, that's what people (bosses) have set up as the primary next target for CloudDB.

**Comment by djavorszky** [comment]
Yup, I agree. That said, SQL Server should be easier. According to https://github.com/golang/go/wiki/SQLDrivers, there's https://github.com/denisenkom/go-mssqldb which we could leverage easily, as it doesn't use cgo, so it should be as straightforward as mysql or postgres.

**Comment by sorin-pop** [comment]
Hi Dani, here are some commits. Most of it is implemented, but we might do further fixing, improvements, etc. I couldn't test it properly yet, because of issue #76. But it's a lot of new code and I wanted to send it as soon as possible.

https://github.com/djavorszky/ddn/pull/77

**Comment by sorin-pop** [comment]
Here is a (final) pull request for mssql implementation: https://github.com/djavorszky/ddn/pull/82

**Comment by djavorszky** [comment]
Merged, thanks! :-)
