### ISSUE TITLE
Failed import was not deleted after 2 days

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#192]
It seems there is a record for a failed import that was not deleted after 2 days (DEGUSSA93_tibi).

@djavorszky can you please clean it manually from the metadatabase? The connector is clean, there's no such user/tablespace there. (of course, if you have time you can also look into why it was not dropped after 2 days, maybe there is some bug somewhere)

![capture](https://user-images.githubusercontent.com/7113037/29916989-c4807e0c-8e40-11e7-92ba-8a3a0135c658.PNG)

**Comment by djavorszky** [comment]
I'd like to wait until EOD - Checks happen every 24 hours, starting from the time the connector was started, so it's entirely possible that it will be deleted sometime during the day.

**Comment by sorin-pop** [comment]
Oh, I see...

**Comment by djavorszky** [comment]
That said, this is confusing, as one would expect the database to be dropped, as it's already 31st of Aug.

I think we should switch up the logic: instead of every 24 hours starting from whenever the connector started, it should run at a predetermined time every day

**Comment by sorin-pop** [comment]
You were right Dani, the record has been deleted, it's not there anymore. I am closing this ticket.
