### ISSUE TITLE
Make sure database is dropped on the day it expires

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#193]
Issue spawned from #192 

With current logic, it is possible that a database that expires on day X will only be dropped on day X+1, which can be a bit confusing, as on day X+1, users see that there's still a database that should've been dropped on day X.

The reason is because the goroutine that checks this runs every 24 hours starting from when the server was started. If a database expires on the same day but after the checking time, then it'll only be deleted the next day.

To resolve this, current logic should be altered: 
Instead of checking whether the expirydate is earlier than the time the check happens, it should check whether the day of expiry is the same as the current date, and if so, drop.

Additionally, it would be nice if it ran at a predetermined time instead of 24h after server startup.

**Comment by sorin-pop** [comment]
I'll give this a try.

**Comment by sorin-pop** [comment]
Pull request: https://github.com/djavorszky/ddn/pull/203

**Comment by djavorszky** [comment]
Closed via #203, thanks!
