### ISSUE TITLE
Persistent DBs

### ISSUE THREAD

**Issue by zsoltbalogh** [djavorszky/ddn#195]
It would be great if we could setup DBs which are not deleted every months. I'd like to move the reporting databases to clouddb.

**Comment by sorin-pop** [comment]
I can try implementing this. My plan would be:
- on the databse import/creation form, under the "Make this a public database" checkbox would be a new checkbox: "Make this unexpirable" (or something similar, if this wording is not good), unchecked by default
- if the user checks it, then we store null in the expiryDate column of the databases table, and the if necessary, accordingly modify server/process.go's maintain function to handle the case when expiryDate  is empty (not do anything in this case)
- or we store a concrete expiry date well in the future (2050 or something), and then we don't have to modify process.go
- when the user leaves the box unchecked, the current behaviour is kept (expiryDate is filled with createDate + 30 days)

- we should also figure out if we want/need an additional feature related to this, namely if we want to make unexpirable an already existing database, from the screen where the databases are listed, as a new action performable on any database (and vice versa, making it expirable, if currently it is unexpirable). Of course, I guess only the owner of a database could do this, and he could not do this switching for databases he did not create.

Any thoughts?

**Comment by sorin-pop** [comment]
Or Zsolt could just tell us which databases he wants unexpirable, and we manually update its expiryDate to a distant future date with a simple UPDATE in the meta database. I'm not sure its worth implementing all the above if we don't really expect that users will use it, and only Zsolt needs it for a few well defined databases. What do you say, guys?

**Comment by djavorszky** [comment]
I think we should go with the now+50 years approach. I would not like to store (and handle) NULL anywhere. Another alternative would be to introduce a new column in the table called "permanent" and just have a 0 or 1 there. Either way we're going to implement this, there are a couple of things we should be considering, namely:
1. We should first discuss whether we want to allow everyone to add permanent databases or not. If so, we need to first implement user authentication and roles.
2. Users should be allowed to create a database as either temporary of permanent
3. Users should be able to make a temporary database permament and vice versa
4. Users should not be allowed to extend the expiry of permanent databases, at least on the UI.
5. Only the database's owner is allowed to make a temp database permanent or vice versa

**Comment by sorin-pop** [comment]
> I think we should go with the now+50 years approach. I would not like to store (and handle) NULL anywhere.

Agree.

> Another alternative would be to introduce a new column in the table called "permanent" and just have a 0 or 1 there.

Not necessary complication, I think, as the solution above would be just fine, without having to create a new database column.

> We should first discuss whether we want to allow everyone to add permanent databases or not. If so, we need to first implement user authentication and roles.

Seems again like an overkill. Remeber, we don't know if this feature is really necessary and will be widely used. It seems to me like it is just a special request for Zsolt. 

> Users should be allowed to create a database as either temporary of permanent
See above:

> on the databse import/creation form, under the "Make this a public database" checkbox would be a new checkbox: "Make this unexpirable" (or something similar, if this wording is not good), unchecked by default

> Users should be able to make a temporary database permament and vice versa
See above:

> we should also figure out if we want/need an additional feature related to this, namely if we want to make unexpirable an already existing database, from the screen where the databases are listed, as a new action performable on any database (and vice versa, making it expirable, if currently it is unexpirable). 


> Users should not be allowed to extend the expiry of permanent databases, at least on the UI.

Agree.

> Only the database's owner is allowed to make a temp database permanent or vice versa

See above:

> Of course, I guess only the owner of a database could do this, and he could not do this switching for databases he did not create.

Do you have any thoughts regarding:

> Or Zsolt could just tell us which databases he wants unexpirable, and we manually update their expiryDate to a distant future date with a few simple UPDATEs in the meta database. I'm not sure its worth implementing all the above if we don't really expect that users will use it, and only Zsolt needs it for a few well defined databases. 

I still think that this is just something that Zsolt will need for a few specific databases, it's almost superfluous further "adorning" CloudDB's UI with a feature that is not really needed by the majority of users. I'm not really a fan of coding just for the sake and "thrill" of coding, as you might have noticed by now ;) But if Zsolt thinks he will need to use such a feature quite frequently even in the future (and not having to ask us every time to run an update in the meta database), then yeah, I guess we should implement it.

**Comment by sorin-pop** [comment]
Besides, users might instinctively abuse this feature, somehow think that it's better to create their databases as non-expirable ("ami biztos az biztos, es nem kell majd bajlodnom hosszabitassal"), which could eventually lead to a lot of unnecessary, unused db's staying in the cloud and taking up space.

**Comment by djavorszky** [comment]
> I still think that this is just something that Zsolt will need for a few specific databases, it's almost superfluous further "adorning" CloudDB's UI with a feature that is not really needed by the majority of users. I'm not really a fan of coding just for the sake and "thrill" of coding, as you might have noticed by now ;)

Sure, makes sense, but what you should understand is that this project may be used by others for other purposes, not only for what it is used now. It's true, that the current requirement is that the databases should be dropped after 30 days unless stated otherwise, but this may not be true for other users, like Zsolt's example. In addition to that, other potential users may be put off from using this service exactly for the reason that they need to do housekeeping every 30 days (note: this is the same reason I'm not using our shared /tmp folder, as it also gets cleared every month).

In this sense, it's not coding for the thrill of it, it's more like enabling our users to use the service in ways that we currently don't imagine that they would. Also, implementing this would not hold back anything else, as we're operating with a relatively fast release cycle (when we have time to actually work on the project, that is).

IMHO we need user authentication and roles for this, but not right now. For now, I've updated Zsolt's database to expire in 2050.

**Comment by zsoltbalogh** [comment]
Thank you! What do you guys think about proving an URL I can hit every day which pushes the deadline out by one day for the DB? (Basically when I call the URL it should add +30 days to expiration). 

This way I can add this call to the importer script which runs every day. So once we tear down the service as not needed, we would simply forget to run this script so it would be dropped in 30 days.

**Comment by djavorszky** [comment]
You can do it right now actually, it's what the extend expiry button does; simply call <host>/extend/<dbid> - calling it sets the expiry to now + 1 month.. Which I just did for your database, so it got reset back to a month from now instead of 2050.

**Comment by zsoltbalogh** [comment]
Thank you, I've added it to my script, this is a good solution for me.
