### ISSUE TITLE
Front end DB name validation no longer working

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#201]
Somewhere along the line the database name validation broke (possibly at the form reorder).

To reproduce, simply type in "test-database" when creating/importing a db and notice that there are no errors (the dash is not allowed for mysql for example)

**Comment by balcsida** [comment]
Because I'm lazy, I'll implement an [input pattern](https://www.w3schools.com/tags/att_input_pattern.asp) to do this

**Comment by djavorszky** [comment]
Sounds good to me. Also, can we merge this with #137?

**Comment by djavorszky** [comment]
Though note: database servers have different strings that they allow as schema/database names, so making the input validation static may not be the best course of action.

**Comment by djavorszky** [comment]
Causes issue with dropping database as well... Though creation will ultimately fail due to MySQL, the meta-information will be shown. Which, when trying to drop the database, will fail again at MySQL due to the wrong name, so dropping won't work either.

**Comment by balcsida** [comment]
Thanks for the heads up!
I'll prioritize the ticket accordingly.

**Comment by djavorszky** [comment]
Actually, disregard what I wrote: if creation fails, metadata is not saved, only shown... so now I'm wondering how that specific database (which has a dash in its name) was created and its metadata saved in the first place? ...might be different issue.

**Comment by djavorszky** [comment]
There was a JS error that got introduced as a regression with #149 - the default selected agent was empty, which resulted in the code trying to call toLowerCase() on a null object - after that part, the rest of the JS broke, taking with it the validation one.

Fixed it with b67e19885a92f188d8fa7c97b6aab1008fdba1c6

That said, it only disables the buttons if the content is invalid, i.e. there's a hypen in the name of the database name, but there's no indication as to what's wrong, so we should still add something like that.

**Comment by djavorszky** [comment]
We should also add backend validation to be honest, as JS and html "disabled" state can easily be circumvented.

**Comment by djavorszky** [comment]
Also, it can still be worked around:
1. Specify name like "test-database"
2. Select agent
Result: Button will be clickable, even though the name is invalid.

Need more robust implementation..

**Comment by balcsida** [comment]
I think this should do the trick:
`pattern="[a-zA-Z0-9_]+"`
It allows all alphanumeric characters and underscore, but disallows any whitespace (so it also fixes #137 )
