### ISSUE TITLE
Change default database type to "public"

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#210]
@NorbertKocsis proposed that we should change the default database type from private to public.

The reasoning was that rarely if ever did he want a database to be (very) private, and he believes that others are in the same shoes.

What do you guys think, @balcsida, @sorin-pop? I'm all for this change, though users should be educated if something like this gets pushed to live.

**Comment by sorin-pop** [comment]
I also usually rather create public databases. I guess Norbi's got a point. So I'm not against this change, I don't really see any strong counter-argument. But perhaps you could conduct some kind of poll, statistics to get a better idea how the users are using CloudDB from this point of view.

**Comment by sorin-pop** [comment]
In LiferayUP, when choosing CloudDB for the database location, we currently create it as a private one by default. So we should also think about this. Should we leave it like this, or should we create it as public from here as well, in case we do this?

**Comment by djavorszky** [comment]
According to the responses in the feedback form, the default database visibility being created is about half public, half private. As such, I think we could implement a property/checkbox something that the user could configure whether they want the database to be public or private by default (which they can then change, of course)

**Comment by NorbertKocsis** [comment]
That's surprising. But the solution sounds nice :)

**Comment by djavorszky** [comment]
Migrated to new location
