### ISSUE TITLE
Archive file not recognized as importable

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#213]
tar.bz2 archives are not recognized as importable.

Are such files unsupported, or is this a bug?

**Comment by djavorszky** [comment]
Only tar, zip and gunzip ate implemented, so bz2 is a missing feature.

Also, went ahead and updated your comment, please don't share customer specific information.

**Comment by sorin-pop** [comment]
Well, how could I have othewise provided reproduction steps about the actually occuring issue?...

**Comment by djavorszky** [comment]
See updated description. The filename is not important when deciding whether a file is importable or not. If in doubt, send a separate email with the actual steps.

Don't get me wrong, I'm thankful for you reporting these issues, but I want to avoid leaking information wherever possible.

**Comment by djavorszky** [comment]
See https://github.com/djavorszky/ddn/blob/master/server/brwsr/brwsr.go#L137

**Comment by sorin-pop** [comment]
Pull request: https://github.com/djavorszky/ddn/pull/262 (also tested)

**Comment by djavorszky** [comment]
Merged, thanks!
