### ISSUE TITLE
"404 page not found" when clicking on a subfolder in the FTP server

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#214]
When browsing for a dump file on the (ftp) server, stepping into a subfolder with at least one period character does no work and errors out with "404 page not found".

The issue was discovered after a user manually unpacked a tar.bz2 file, resulting in a folder with period characters in it.

**Comment by djavorszky** [comment]
Most probably due to the period in the name of the folder not being an accepted character according to business logic. Can you please test if this is the case and if so, update the description to remove references to the customer?

Thanks

**Comment by sorin-pop** [comment]
Yep, seems like that's the issue, according to my further tests.

**Comment by djavorszky** [comment]
Yeah, that's the issue, the period is not an allied character there:
https://github.com/djavorszky/ddn/blob/master/server/routes.go#L97

I believe it should be

**Comment by sorin-pop** [comment]
I'll take this one.

**Comment by sorin-pop** [comment]
Note for myself: https://regexr.com/

**Comment by sorin-pop** [comment]
Pull request: https://github.com/djavorszky/ddn/pull/215

I could not test it, as I could not start a local server: something about some disco... Perhaps you can help me with that.

I also couldn't really figure out how to use reger.com, I think.

**Comment by djavorszky** [comment]
Merged via #215, thanks!
