### ISSUE TITLE
Enable CloudDB to send web push notifications

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#216]
...if the users want to receive them. They can enable/disable them anytime from the CloudDB UI.

I think it would be a cool and modern feature.

I have implemented it at a minimal level. Further refinements can be discussed and done later on, there are many possibilities with how a notification should look like and what the user can do with it. As I implemented it now, they would receive them when:
- an import has finished (successfully or not)
- a database has been dropped (either by direct user action, or by the back end scheduler)
- warning that a database will be dropped in one week (for example here we could add the possibility for the user to extend right from the notification)

So pretty much when they would receive an email as well.

You can view a short demo at https://drive.google.com/file/d/1VMLe-nsGhgg3dx0LV2p40q0X19tv6cuC/view

You can read more details on the subject and the technology behind it at https://developers.google.com/web/fundamentals/push-notifications/

As you can see there, there is one tiny "problem" with it:

> Unless you're using localhost, the Push API requires HTTPS.

But I hope you'll like the feature idea enough to be willing to put CloudDB on https sometimes in the near future, if possible. (as far as I know, it is on http currently)

Please let me know if you have any questions and if I can send pull request.

**Comment by balcsida** [comment]
++++++++++++++++++++++++++++++++100000

**Comment by djavorszky** [comment]
Disclaimer: I don't really use push notifications on desktop, haven't really found a situation where it would be beneficial.

But you have, this is amazing. If it requires HTTPS then HTTPS it will get. If nothing else we'll use a self-signed cert. I'll go and open a new issue for this and also one for IT.

**Comment by balcsida** [comment]
@djavorszky we can use Let's Encrypt for this matter if:

- liferay.int is a valid domain name
- cloud-db.liferay.int can be resolved externally (no need to display actual content, the default "It works" is fine)

**Comment by djavorszky** [comment]
@balcsida please cross-post that to #217 :-)

**Comment by sorin-pop** [comment]
Here is a pull request: https://github.com/djavorszky/ddn/pull/218

In addition, the following section needs to be added to the server's config file (server.conf is excluded from git for me, for some reason):

##
## Web Push Notifications
##

    #
    # Specify the application server public and private keys (so-called VAPID keys) used for
    # communicating with the Web Push Notification service providers used by browsers.
    # The public key is used in res/js/push.js, and is used by the browser when subscribing
    # to receive push notifications. If you update it here, make sure to update it in push.js as well.
    #
    # The private key is used when the back end is sending a notification (push.go)
    #
    # You can create a public and private set of application server keys by visiting 
    # https://web-push-codelab.glitch.me/ or you can use the web-push command line (https://github.com/web-push-libs/web-push#command-line)
    # to generate keys by doing the following:
    #   $ npm install -g web-push
    #   $ web-push generate-vapid-keys
    #
    
    vapid-public-key = ""
    vapid-private-key = ""

**Comment by sorin-pop** [comment]
And in sw.js need to change http://localhost:7010 to the real production URL.

**Comment by djavorszky** [comment]
Thanks for implementing this @sorin-pop!

Merged with some changes, like running the source formatter as well as some minor logic changes... plus added tests to the db logic.

I noticed that this works for Chrome but doesn't seem to work for Firefox.. We should look at why this is to be honest.

Also I think we should think about replacing the button to an icon or something similar that doesn't really push the header to the left and is responsive as well (e.g. collapses into a dropdown on mobile)

**Comment by sorin-pop** [comment]
Fine with me.

Hmmm...we definitelz should look into whz it doesn!t work for Firefox...because theoreticall it should, Firefox supports such functionality.

**Comment by sorin-pop** [comment]
I tested again with Firefox, indeed it was not working. But as it turned out, again because of that damn contains() method in sw.js. I corrected the sw.js file and then I manually updated the service worker belonging to it at about:serviceworkers. After that is was working fine.

It seems like this updating of the service worker on the client, when there was a change in it, is kind of shaky. I'll look better into this, because we cannot expect users to do this update manually from some "hidden" places in their browsers every time we will be making further changes to the service worker sw.js. We should be able to control this centrally somehow.

**Comment by djavorszky** [comment]
Don't spend too much time on that, once we put it into production, it will be a tested and working configuration with hopefully minimal cause for changing it. Because of this I don't think manually updating the service worker will be required by users in the near future.

I'll retest again tomorrow.. I think the main issue was the stale service worker on my side as well, at least that's what I'm hoping.

**Comment by djavorszky** [comment]
Just verified on master - after disabling and reenabling the service worker, push notification works!

As I mentioned, this had to be done only because we've had updates to the service worker since it wasn't working before. As such, this won't be an issue once we're in prod.

I consider this to be completed and implemented, thank you very much @sorin-pop, this is an amazing feature!

One last thing though.. @balcsida, I'd like to pick your brain about where and how to place this button.. the current location isn't the best imho, I'd rather see if we can place it somewhere better. The hard part is that it's being updated by js (in https://github.com/djavorszky/ddn/blob/master/server/web/res/js/push.js), so it's not a trivial thing to simply replace it to an icon for example.

**Comment by sorin-pop** [comment]
I think it's important to be prepared that we will change the service worker in prod. That's exactly the place where we "catch" the notifications and display them, and as such, I find it very probable that we might want to make changes to this part: there are a lot of possibilities here, especially about how to display the notifications, what to appear in them, perhaps adding some options for the user, etc. I really can imagine that we will want to make changes/enhancements here, with a very big probability.

And the update of the service worker should work seamlessly, that's how it works with some examples I worked on. We just have too figure out why it doens't work for our implementation. So I think I will continue looking into this. So far what I could find as a possible root cause, is that I put the sw.js under res/js folder, because I saw that the other js files were there, so I thought it will be better organized like this. But in all the examples/tutorials I worked from, they were actually always putting the service worker js file under the web app's root, and I think this might be important. I tried this a little bit with our CloudDB app, but then I encountered the problem that it would not find the sw.js file anymore, if I placed it somewhere else than under the res folder. In push.js, this statement for example, after I moved the sw.js file under the web folder:

navigator.serviceWorker.register('sw.js')

was failing with 404 http code. I'll continue looking into this, probably will open a separate ticket for it.

**Comment by balcsida** [comment]
Hi everybody,

I apologize for the big time gaps between my comments.

Regarding the notification stuff et al: I'm not against using an external, third party lib for this. Or I would say, I would be more happy to use an external library, as those can overcome the differences between browser implementation of Service Workers.
My recommendation would be PushJS: https://pushjs.org

@djavorszky : IMHO, there is no need to have a button as all browser have native permission request modals. Just call it onLoad() and the user will decide it.
![image](https://user-images.githubusercontent.com/1768446/33179421-a5a5b874-d069-11e7-8d6e-cfe969d313a0.png)

Best regards,
Dávid

**Comment by sorin-pop** [comment]
Hi David,

Please see https://developers.google.com/web/fundamentals/push-notifications/permission-ux for why I have decided to rather implement a button on our UI for this. According to this article, what you are suggesting is not a recommended way of doing this, it is actually unrecommended and mentioned as a bad example of doing it. Just think of the following: a user who subscribed realises after a while that actually the notifications are bothering him, and would like to get rid of them, disable this functionality. Without a proper way to do this on our UI, they will need to figure out how to disable this from the browser itself (if they will realize that this is possible at all). But once again, see the article above for, I think it's a very good one, with very nice ideas and explanations on how to do this "elegantly".

**Comment by djavorszky** [comment]
I agree with @sorin-pop, in the sense that I wouldn't want automatic push notifications. Whenever a site does that my immediate reaction is "no, don't spam me".. even if in the end the push notifications would be be great. Also, clicking the button simply brings up the browser confirmation..

Regarding pushjs.org, as I can see it uses js to trigger sending push notifications - which is a bit unfortunate as we're triggering the push notifications from the backend.

I have an idea for the UI: have an icon next to the username, like a clear/filled ligthbulb (something from font awesome) - onclick should bring up an overlay which houses the link/checkbox/toggle/something. This way we're not wasting (too much) space, nor do we have to make sure the button/link/whatever conform to Bootstrap's <nav>.

What do you think?

**Comment by sorin-pop** [comment]
I can't quite imagine how this will look like, but I guess @balcsida can make it beautifully.

Just please make it very easy and obvious for the user to understand what the light bulb button is about, and cover all the four possible states that are already implemented (pushButton.textContent in push.js):

1. Enable Push Notifications --> Light bulb not burning, and clickable, with a mouse hover tooltip saying something like "Enable receiving push notifications whenever a database import/export has succeeded or failed, as well as when a database is scheduled for removal or has been deleted manually/automatically". Yeah, I know, looks a bit too much perhaps. I like if all info is given to the user, to be sure he understands what that stuff is for. But I'm open for any other suggestion.

2. Disable Push Notifications --> Light bulb burning, and clickable, with a mouse hover tooltip saying something like "Stop receiving push notifications whenever a database import/export has succeeded or failed, or when a database is scheduled for removal, or has been deleted manually/automatically"

3. Push Not Supported --> Light bulb not burning and not clickable, with a mouse hover tooltip saying something like "This browser does not support push notifications. Please use a browser that does, in order to enable them." Or, don't show the bulb at all. (By the way, I just seem to realize now, that here I should have probably disabled the button. Looks like I didn't, so this is a small bug I guess. )

4. Push Notifications Blocked --> Light bulb not burning and not clickable, with a mouse hover tooltip saying something like "It seems that previously you have completely blocked push notifications for this site. You can re-enable the possibility to turn them on through your browser's notification settings for this site (in Chrome or Firefox simply click to the left of the site URL in the navigation bar, and in the Notifications section choose Ask (recommended) or "Always allow on this site". Then you should be able to click this button, and this time choose Allow (not Block) in the browser pop-up question , which appears if you chose Ask before)

**Comment by djavorszky** [comment]
Thanks for the inputs Sorin! The original idea was for a lightbulb icon or something similar that brings up a modal-window like area with information and a toggle checkbox, but then I thought about this and realized that this could be nested under a "user preferences" type section, next to the "default database should be private/public" (a la #210). This could be similar to how Liferay 7 does its control panel/navigation (E.g. click a button to bring up a tab from the left), in the sense that it wouldn't be visible on the page by default, only if a button is clicked.

This way we could provide adequate information without cluttering the UI with information that isn't quite necessary to be there all the time.

As for what to show: Text and a checkbox (or toggle or button). IMHO text should always read "Push notifications" with the following values for checkbox/toggle/button (whichever looks better):
1. Enabled: Checkbox ticked / toggle in "ON" / button reads "Disable"
2. Disabled: Checkbox not ticked / toggle is "OFF" / button reads "Enable"
3. Blocked: Checkbox not ticked, disabled, with mouseover text 'Blocked' / toggle is "OFF", disabled, with mouseover text 'Blocked' / button reads "Blocked", disabled
4. Not supported: Either Push Notification option is not shown at all, or there's only a text saying "Push notification not supported"

All these would require some database updates as well, new table perhaps, to house user preferences.

**Comment by sorin-pop** [comment]
Yes, I agree with this approach, to put all this in a separate "settings" panel/page (where we later can even put more granular possibilities, like only send notifs when importing a dump, but not when, for example, the backend automatically deletes an expired db. And this panel/page could host other settings as well, as you mentioned). Actually this is how I originally imagined it, I just implemented it like this (with the button directly on the main screen) because it was much easier and faster. I wanted to focus rather on the functionality itself, to make sure that I can make it work at all. At that time it was of secondary concern where we put that button, and if it should be a button or toggle or checkbox. But now we can improve on that part, and I do agree, that it all should be in a separate Settings page/panel, like you described. By the way, I would vote for toggle.

@balcsida what's your opinion?

**Comment by balcsida** [comment]
Hi!
Sorry for not responding again.
I'll read all of your comments during the weekend and will try to figure out something for that.

**Comment by balcsida** [comment]
Still did not have time for reading the comments, dammit.
I would like to ask your kind patience.

**Comment by djavorszky** [comment]
No need to rush.. enabling this requires #217 anyway, which also depends on our IT dept, so this feature may only go live early next year.

**Comment by sorin-pop** [comment]
Just as a reminder:
- is there any progress with enabling https for CloudDB? Is IT working on it?
- @balcsida, did you have the chance yet to think about the UI stuff we discussed?

**Comment by djavorszky** [comment]
Migrated to new location
