### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#217]
Currently there's only option to run CloudDB on HTTP. This is an issue as for example #216 would require HTTPS to function. Not to mention that it's a best practice to use HTTPS whenever anyway, especially if we're going to add user authentication at one point or another anyway (see #54).

There are two ways we can go about adding HTTPS:
1. Put CloudDB behind a web server that has HTTPS configured
2. Add HTTPS capability to CloudDB itself.

# Put CloudDB Behind web server
This is the current case, traffic to CloudDB is sent through an apache (or nginx?) server. Current arch is http->http though, so if we change the first part (https->http), we'd need to change CloudDB to generate correct URLs.

The downside is that we don't really have control over the web server. The upside is that minimal change is required in CloudDB.

# Add HTTPS capability to CloudDB itself
As far as I know, using this approach we wouldn't need to change too much on the web server as that's only acting as a proxy. CloudDB will need some configuration update, certifications and URL changes depending on whether http or https is used.

The downside is probably more work to make it happen (though I believe adding https support in Go should be a breeze), the upside being no or minimal need to change the web server.

**Comment by balcsida** [comment]
@djavorszky we can use Let's Encrypt for this matter if:

- liferay.int is a valid domain name
- cloud-db.liferay.int can be resolved externally (no need to display actual content, the default "It works" is fine)

**Comment by djavorszky** [comment]
Just checked, adding HTTPS support is a trivial change as long as we have certification files: https://golang.org/pkg/net/http/#ListenAndServeTLS

**Comment by djavorszky** [comment]
Well, according to https://en.wikipedia.org/wiki/.int, .int _is_ a valid TLD, however it stands for international instead of internal (which kinda makes sense).

Let's involve IT in the discussion.

**Comment by sorin-pop** [comment]
Hi Dani, any progress on this? Has IT been involved?

**Comment by djavorszky** [comment]
Yes, see LRHU-836

**Comment by sorin-pop** [comment]
Well, there's nothing on it. No feedback whatsoever from IT yet. The ticket was opened, and that was that. We could probably just wait until we get old, and still nothing would happen.

I asked in a comment if they have any news. (do you think they will reply? :))

To be honest, I'm quite pissed off with this extremely slow reaction, or no reaction, no involvement, related to almost anything we ask from them or try to involve them into. They really don't seem to be of any use at all. (OK, they did a few stuff, like giving more space to the db servers, after a while. But generally, it's rather this absolute lack of feedback and action that I see.)

**Comment by djavorszky** [comment]
Migrated to new location
