### ISSUE TITLE
Oracle DBName differs from username

### ISSUE THREAD

**Issue by vilmospapp** [djavorszky/ddn#219]
If new DBName is not specified, Cloud DB will generate different name for the entry and for the username.
e.g.:
Name: side_output

Portal-ext:
```
jdbc.default.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.default.url=jdbc:oracle:thin:@192.168.211.213:1521:orcl
jdbc.default.username=tag_electric
jdbc.default.password=gel_audible
```

**Comment by djavorszky** [comment]
Per my understanding this should not happen - database name should be made equal to user name in case of oracle, as this is how it works when you specify the username.

**Comment by sorin-pop** [comment]
Pull request sent: https://github.com/djavorszky/ddn/pull/224

Not sure if it's the best solution. I was hoping to handle it in one place, in the ensureValues method, but then it didn't look like suitable for this, unless I would have largely rewritten it.

**Comment by djavorszky** [comment]
Merged, will push to prod in January. Thanks!
