### ISSUE TITLE
Adding an Oracle user with hyphen fails with error 500

### ISSUE THREAD

**Issue by alfonsocrisci** [djavorszky/ddn#220]
Steps:

1) Go to http://cloud-db.liferay.int/createdb
2) Database: oracle-12
3) Database user: my-db (or any names with a hyphen within)
4) Database password: password
5) Hit "Create"

**Actual behavior**: DB creation fails with message on screen:

`sending json message failed: got non-200 response '500' and message: {"status":305,"message":"creating database \"my-db\" failed: unable to create database:\n\u003e stdout:\n'\r\nPL/SQL procedure successfully completed.\r\n\r\n\r\nPL/SQL procedure successfully completed.\r\n\r\nBEGIN\r\n*\r\nERROR at line 1:\r\nORA-02180: invalid option for CREATE TABLESPACE\r\nORA-06512: at line 2\r\n\r\n\r'\n\u003e stderr:\n''\n\u003e exitCode: 2180"}`

**Expected behavior**:

1. DB creation to succeed (provided that Oracle allows that, I only found https://docs.oracle.com/cd/E19082-01/819-2379/6n4m1vlba/index.html so far), OR
2. Clear validation error on Database user field immediately when typing, OR
3. A simpler error message explaining the reason for the failure

Thank you !

**Comment by djavorszky** [comment]
Thanks @alfonsocrisci!

Already have #208 for prettifying the error message and #201 for validation no longer working.. Having another report about this causing an issue helps us prioritize fixing the issue.

I'll leave this one open so that we remember to test this usecase as well.

**Comment by alfonsocrisci** [comment]
Thanks Dani ! This was just to help your work and I saw it was indeed the case, I really leave the choice to you guys on how to (and whether) fixing this :)

**Comment by djavorszky** [comment]
This has just been fixed on trunk via b67e198 - there was a JS error that broke the validation. This adds a rudimentary protection against invalid characters, I'll close this ticket and focus on making a more robust implementation on #201.
