### ISSUE TITLE
Implement api/list-agents and deprecate api/list

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#233]
The current `api/list` endpoint returns a key-value pair of agent_name:dbvendor.

The new `api/list-agents` endpoint returns a key-value pair of agent_name:{everything about the agent}

@sorin-pop: Once this is in, api/list will be deprecated.

**Comment by sorin-pop** [comment]
OK. Could detail what will be in the {everything about the agent} part, with a concrete example as well? So that we can accordingly change the code in LiferayUP. Thanks.

**Comment by djavorszky** [comment]
Sure! I just added an [api.md](https://github.com/djavorszky/ddn/blob/master/server/web/html/api.md) / [api.html](https://github.com/djavorszky/ddn/blob/master/server/web/html/api.html) that will be served from the /api endpoint. I've outlined examples for both how to call the endpoints and what the results look like.

I intend to keep them up-to-date as well.

**Comment by djavorszky** [comment]
Also, I can open a new issue for LiferayUP with the exact details if you wish. Same goes for #235.

**Comment by sorin-pop** [comment]
Yes, please. thanks

**Comment by sorin-pop** [comment]
I opened the corresponding [LiferayUP ticket](https://github.com/vilmospapp/liferay-support-ee/issues/381). @djavorszky , please let me know when this has been finalized.

Thanks.

**Comment by djavorszky** [comment]
Implemented, closing
