### ISSUE TITLE
Import for public database tomcsiLPP28389 failed

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#239]
@djavorszky , any idea?

Tomcsi made another one after that - tomteszt -and that one went without problem.

**Comment by djavorszky** [comment]
No idea. I mean I see the error:
```
2018/01/09 12:03:16 [error] could not import database: could not execute import command: psql: FATAL:  database "tomcsiLPP28389" does not exist
```

Do we know if either of these were file upload or server browser imports?

**Comment by djavorszky** [comment]
The error is coming from the "startImport" function which is only called from one location: agent/handlers.go/importDatabase. Immediately before starting the startImport in a goroutine, we create a new database. If that were to fail, the whole process would return.

I'll keep looking

**Comment by djavorszky** [comment]
Ok, I see now. Create DB call can fail successfully.. that is, say it succeeded but fail. Not sure why though, but I can reproduce such an issue with the name "tomcsiLPP28389".. and it's not the length ("testingwithverylongdatabasename" was successful)

**Comment by djavorszky** [comment]
This is an issue with case sensitivity. Looks like postgres creates the databases in lower-case way, whereas importing seems to happen in a case-sensitive way.

**Comment by djavorszky** [comment]
Per [this link](https://www.postgresql.org/message-id/4989FA67.4010706%40archonet.com):
> CREATE DATABASE Test1   => test1
> CREATE DATABASE TEST1   => test1
> CREATE DATABASE "Test1" => Test1

This seems to be what's happening at our side, as I'm not quoting the database names.

**Comment by djavorszky** [comment]
Fixed, postgres agent updated, confirmed that database is imported correctly with name `tomcsiLPP28389_2`
