### ISSUE TITLE
Popovers no longer working in Firefox, Chrome

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#240]

**Comment by djavorszky** [comment]
Sometimes works, sometimes doesn't. Can't see a pattern..

**Comment by djavorszky** [comment]
Closing as too much effort would be required

**Comment by balcsida** [comment]
My apologies for being inactive here.
Upgrading to the latest Bootstrap should resolve the problem (we still use 4.0 beta)

**Comment by sorin-pop** [comment]
So the trick is to close the tickets in order to trigger activity from David... :) I might apply this method on a few other tickets (actually I was already thinking about it)

**Comment by balcsida** [comment]
You got me there. Yep, when there is activity on the tickets on weekends, I am being more active (because I get email notifications).
