### ISSUE TITLE
Cannot import create-insert-all.sql

### ISSUE THREAD

**Issue by sebastian-madaras** [djavorszky/ddn#245]
path: r2d2:\ftp\CLOUDDB-0\

error message:

Import database failed
Your request to import a(n) "mysql" database named "mydbname" has failed with the following message:

"Importing dump failed: could not execute import command: Warning: Using a password on the command line interface can be insecure.\nERROR 1170 (42000) at line 1864748: BLOB/TEXT column 'samlIdpSpSessionId' used in key specification without a key length"

We're sorry for the inconvenience caused.

Visit Cloud DB.

**Comment by djavorszky** [comment]
We've checked the dump in question - it seems that for one reason or another, the create table queries are added to the dump multiple times.
