### ISSUE TITLE
Production Oracle agent no longer writes debug messages

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#247]
I just noticed this... @djavorszky  any idea why?

It used to write out debug messages about what command it was running, etc., which sometimes can be helpful.

I had a look at util.go and I still can see there, in func RunCommand, the line:

logger.Debug("Running command: %s %s", name, args)

Has anything changed about logging, some new configuration needs to be made perhaps?

**Comment by djavorszky** [comment]
Default has been changed to info. To change it, call /api/loglevel/debug on the agent.

**Comment by djavorszky** [comment]
note: server api updated to use "PUT" method instead of "GET". Documentation added to [api doc page](https://github.com/djavorszky/ddn/blob/master/server/apiv2.md#put-apiloglevellevel).

not live yet + agent not affected (yet)

**Comment by djavorszky** [comment]
Closing as answered, do let me know if you have further questions though

**Comment by sorin-pop** [comment]
Hi Dani,

"call /api/loglevel/debug on the agent"

Could you please be more specific on how to do this? I thought this API endpoint is for the server. How do I call it for an agent?

**Comment by djavorszky** [comment]
simply GET http://agent-url:agent-ip/api/loglevel/debug

**Comment by sorin-pop** [comment]
Thanks! It worked!

**Comment by djavorszky** [comment]
Note though that the default is still set to "INFO", so you'll have to do the same after restart. You could change the default at build time [here](https://github.com/djavorszky/ddn/blob/master/agent/main.go#L51).
