### ISSUE TITLE
Agent for DB2

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#249]
Couple of people asked me to add DB2 support as that's one of the biggest painpoint they have with regards to using supported databases.

For this one, I'd say let's try to implement it in Java.

**Comment by sorin-pop** [comment]
Hi @djavorszky , why do you think we should implement this in Java? Any specific reason?

**Comment by djavorszky** [comment]
There is [no pure-go DB2 SQL driver](https://github.com/golang/go/wiki/SQLDrivers), so implemeting it in Go would require C bindings.

Java requires a JRE and JDBC jar and it's set. I'm fine with Go as well, but the important part is that we don't need to stick to Go if another language makes more sense.

**Comment by djavorszky** [comment]
Migrated to new location
