### ISSUE TITLE
Possible issue with extending expiry

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#250]
I tried to extend the expiry of some of my (public and private) databases. They are all set invariably to February 23, 2018, regardless of the current expiry date. And for any subsequent extending attempts, the expiry date stays at February 23, 2018.

**Comment by djavorszky** [comment]
This is intended. Current logic will update the expiry to now + 30 days.

The [new API](https://github.com/djavorszky/ddn/blob/master/server/apiv2.md#extend-database-expiry) will work differently though.
