### ISSUE TITLE
MySQL dump import fails

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#253]
Importing dump failed: could not execute import command: ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '****.sql ' at line 1

Full error on Skype.

**Comment by sorin-pop** [comment]
I also tried to import it in the 5.7 MySQL, and got this error:

> Importing dump failed: could not execute import command: mysql: [Warning] Using a password on the command line interface can be insecure. ERROR: ASCII '\0' appeared in the statement, but this is not allowed unless option --binary-mode is enabled and mysql is run in non-interactive mode. Set --binary-mode to 1 if ASCII '\0' is expected. Query: 'laptop__20180125.sql'.

It seems to be some special kind of dump, a binary one, which CloudDB might not be able to handle. So perhaps this could be a new feature.

**Comment by djavorszky** [comment]
According to the internet, there is no "binary dump" in MySQL, contrary even to the error message itself.

Per [this](https://stackoverflow.com/questions/17158367/enable-binary-mode-while-restoring-a-database-from-an-sql-dump), we may be looking at an actual zip file - can you try to unzip the file and see if it imports then?

**Comment by sorin-pop** [comment]
Indeed it seems that this .sql file was actually a zip file. After unzipping it, the import seems to be running. Still in progress, but I think we can close this ticket. It was just a tricky dump file we received.
