### ISSUE TITLE
Small inconsistency in the API documentation

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#254]
The title for DELETE /api/databases/${agent}/${dbname} is

"Get metadata of specific database by agent and database name"

Should probably be something like:

"Delete specific database by agent and database name"

**Comment by sorin-pop** [comment]
Yes, I'll do it.

**Comment by sorin-pop** [comment]
Here is the pull request: https://github.com/djavorszky/ddn/pull/256

**Comment by djavorszky** [comment]
Thanks! merged it already.
