### ISSUE TITLE
Rewrite the CloudDBUtil.getDBParameters() according to the new API

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#255]
We should use the GET /api/databases/${agent}/${dbname} API, and I think we can throw out the getAgentParameters() method, as this API will provide everything we need:
-Dbaddress
-Dbport
-sid
-user
-password

**Comment by djavorszky** [comment]
Are you sure you wanted to open this issue in this repository? :-)

**Comment by sorin-pop** [comment]
Uhmmm...no :)

Sorry!
