### ISSUE TITLE
[UX] Able to start db creation without selecting agent

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#260]
Steps to reproduce:
1. Click on "Create database"
2. Type in a name for the database
3. Notice that the "Create" button is no longer disabled
4. Click on "Create"
Result: "Agent went offline" - because no agent was actually selected.

Suggested solution: rework the validation logic in JS to always check whether the necessary fields are selected and valid

**Comment by balcsida** [comment]
Issue migrated
