### ISSUE TITLE
Oracle classic dump imp not-working case found

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#263]
... by @adamzsolnay. He got a classic Oracle dump from a customer and the import failed/didn't create the tables.

I have investigated it and I found the root cause. It seems to be some kind of edge case which did not come up with other classic dumps so far, while I was implementing and testing this. For some reason, with this particular dump, the same imp command gives a slightly different output, one that I did not count on so far (before I never did get this kind of output).

If you are curious, you can see the abstracted description in my stackoverflow post here: https://stackoverflow.com/questions/48754079/oracle-imp-schema-prefix-used-in-file-generated-by-the-indexfile-option

Anyway, it pretty much looks like nobody will be able to answer it properly, so I will probably go ahead and fix this with a somewhat ugly workaround involving parsing through a large text file and editing it (I am already doing that to some degree anyway).

**Comment by sorin-pop** [comment]
Implemented and tested with two kinds of classic dumps. The type it was already tested and working with, and the type received by @adamzsolnay. Now both work. 

(I think the difference between them is that in the first case exp was run by the Liferay user exporting its own objects, while with the new type received by Adam, exp was run by some other Oracle (admin) user, exporting liferay user's objects. This resulted in different behaviour at import time, and therefore import needed to be handled slightly differently for these two cases)

Pull request: https://github.com/djavorszky/ddn/pull/265

**Comment by djavorszky** [comment]
Thank you @sorin-pop and @adamsolnay! I've just merged this.

**Comment by sorin-pop** [comment]
Thank you. I have copied the modified import_procedure.sql file to the Oracle agent in production, and restarted the agent. So now this should be fine in the production CloudDB as well.
