### ISSUE TITLE
(Possibly) Add support for 7zip files

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#266]
Recently a CloudDB user received a dump packed as a .7z file, and accordingly did not see the IMPORT link next to it. (It's another matter the fact that even after unpacking it manually, he could not see the link, because the dump file inside had extension .dump)

Perhaps we could add support for unzipping .7z archives as well, just as recently we added support for bzip2 (.bz2) archives. I looked around a bit, but I could not find a golang library that can handle this natively, but there seems to be one that does it through the 7z executable (which means we would need to install 7z on the CloudDB server):  https://blog.kowalczyk.info/article/g/extracting-files-from-.7z-archives-in-go.html

What do you think @djavorszky , is it worth it?

**Comment by djavorszky** [comment]
A great idea, but requires a lot of effort based on what you found so far..

For now, let's put this on hold. I'd like to first make some architectural changes.

**Comment by sorin-pop** [comment]
Roger that.

**Comment by djavorszky** [comment]
Migrated to new location
