### ISSUE TITLE
Towards a better handling of failed export

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#267]
Currently, if a database export fails, the db record will end up with status "Export failed", and in the current UI implementation, this will render some other operations on that database unreachable, like Extend and Portal-ext info (which should still be available, because the db is still there).

![capture](https://user-images.githubusercontent.com/7113037/36907466-04fd0ab2-1e39-11e8-95ed-6fa69658c554.PNG)

I guess perhaps the db should still end up with Completed status, so that everything is still accessible on the UI. The user will know about the failed export (and its cause) from the email (and push) notification. Anyway I don't think that users will tipically look for this info on the UI. They will start an export, and I don't think they will wait and watch the UI in the meantime. (I, as a user, would be totally OK with this)

But as you think, @djavorszky , we could implement some more sophisticated stuff for this if you want. And I also guess it depends on the new structural changes as well.

**Comment by djavorszky** [comment]
Cross-posting from #191:

Thinking about it, I think the "Completed" status is simply redundant, and we may be approaching statuses the wrong way. The general idea is that a database may be "usable" nor "not usable".

"Usable" would simply mean that clients can connect to it, which is the case when the database has been successfully created or imported, but also when an export is in progress.
"Not usable" would be everything else - import/create in progress, or any failed status.

And then we could sub-status these, e.g. specify why a database is unusable or a usable database being exported at the moment. What do you say? I'm not sure. Just thinking aloud. Also, even if we go with this, I don't like the usable/unusable statuses, they sound silly, so we may want to look for better ones.

**Comment by sorin-pop** [comment]
I agree that in these new circumstances, the current status system seems kind of obsolete and could be re-thinked and re-written somewhat. (Above I tried to give the possible less "intrusive" approach as always, as I am not a big fan of (frequent) core structural changes, as they may affect the stability perceived by users.)
Your proposal seems OK to me (even the Usable/Not Usable status names...I can't think of anything better now)

**Comment by djavorszky** [comment]
I understand your concern - for me, reliability is of utmost importance.

As we're going to go to a new UI anyway, we might as well make some changes on the front end. The backend, as long as it keeps working the way it was before, should only have minimal affect on user perception.. Ideally, at least.

What I've been thinking is to remove the current portal-ext button and instead take the user to a full page where all information is present - database export (if available), portal-exts, info on when the database was imported / created, when it expires, and an event log: e.g. when it was last exported, or in which status did the import fail, things like that.

Sure, it's a big change, but I think we may be able to make it more user-friendly and leave space to add more information in the future.

**Comment by sorin-pop** [comment]
Sounds good to me.

**Comment by djavorszky** [comment]
Ticket merged to new location
