### ISSUE TITLE
Expired database not removed.

### ISSUE THREAD

**Issue by ahika74** [djavorszky/ddn#275]
Dear Engineers,

I would like to report the case where I have 2 databases that have the expiration date on 8th of January 2018. However, their status is "Removal Scheduled"

I am attaching a screen shot.

Best Regards,
Ahmed
![capturedatabase](https://user-images.githubusercontent.com/31508658/37769520-8b683bd8-2dd1-11e8-9d0c-4675353b1138.PNG)

**Comment by djavorszky** [comment]
Thanks @ahika74! I've fixed this issue recently.
