### ISSUE TITLE
Issue with case-sensitive database names and API's

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#276]
> C:\Users\sorin.pop>curl -H "Authorization:sorin.pop@liferay.com" cloud-db.liferay.int/api/databases/mysql-57/kadas2
> {"success":false,"error":["ERR_DATABASE_NO_RESULT"]}
> C:\Users\sorin.pop>curl -H "Authorization:sorin.pop@liferay.com" cloud-db.liferay.int/api/databases/mysql-57/KADAS2
> {"success":false,"error":["ERR_ACCESS_DENIED"]}

The same API call returns  different results for lower and upper case database name. (this confuses somewhat LiferayUP, that's how we noticed this)

Suppose we call the API above with "kadas2" (lower case): it tells us that such a database doesn't exist. So we go on and call the create API, in order to create it. But that fails with:

response:{"success":false,"error":["ERR_DATABASE_CREATE_FAILED","sending json message failed: got non-200 response '500' and message: {\"status\":305,\"message\":\"creating database \\\"kadas2\\\" failed: database 'kadas2' already exists\"}"]}

**Comment by sorin-pop** [comment]
My expectation from LiferayUP point-of-view would be that also for the first API call I get ERR_ACCESS_DENIED. Well, in any case, I should not get ERR_DATABASE_NO_RESULT, because then I wrongly assume that this db doesn't exist, while it actually exists. (and the create API fails, for that reason)

**Comment by djavorszky** [comment]
I've been thinking about this, and you're right in that it should work consistently, which it does not do at the moment.

I think the obvious route is to make CloudDB case insensitive (lowercase everything) and inform everyone about this.

We wouldn't be losing anything with mysql-mariadb databases, as they are already case insensitive... but Oracle is going to be a problem, with maybe postgres also being affected - not sure.

If I only update the API part, it won't resolve the issue you're facing as I'd need to update the database as well.. Which I could do at next startup, but that would break the oracle portal-exts for sure. What do you think, how could we best handle this?

**Comment by sorin-pop** [comment]
For the moment, I don't have any idea. I'm even a little bit confused in regard to this issue.

**Comment by djavorszky** [comment]
Migrated to the new location
