### ISSUE TITLE
Issue with posgres db creation

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#277]
Steps to reproduce:
1. Create a postgres database with the following field filling:
database name - sorintest1
database user - sorinuser1
database password - test
Checkpoint: database is created allright

2. Create a new database with the following field filling:
database name - sorintest2
database user - sorinuser1
database password - test

Result: sending json message failed: got non-200 response '500' and message: {"status":305,"message":"creating database \"sorintest3\" failed: user 'sorinuser1' already exists"}

but the metadata row is created nevertheless, so you can see below that sorintest2 is listed as a Completed, existing db.

Problem 1: the metadata row should not be created
Problem 2: if we want to create a new database with the same user, it should allow it, just like for mysql. So I think that we should remove the db.userExists check from postgres.go's  CreateDatabase func. Just like there is no such check for Mysql either. (and we should also accordingly update CreateDatabase comment in mysql.go, because it still says that we chack for the user existance)

What do you think?

**Comment by djavorszky** [comment]
I agree with Problem 1, it should definitely be fixed.

As for Problem 2, that's more complicated... and I'm a little bit confused as to why we removed it. This about the following scenario:

1. User 1 creates private database "whatever" for user "testUser" and password "test"
2. User 2 creates private database "notimportant" for user "testUser" and password "asdf"

In this case, we allow both databases to be created, both of which will be accessible by the "testUser".

But User 2's meta information will show that the password is "asdf", which is not correct. As a correlation, if User 1 connects to the database server manually, they'll see two databases: their own and "notimportant".

There's no real good way to resolve this.. Any way we go, there's a security issue.. (I know, I know, we don't even have a working login system, that's on my list).

I'd rather be more strict: enforce a one-user-per-agent policy (with a unique key) even before we try to issue the create command to the agent.

What do you think?

**Comment by sorin-pop** [comment]
I don't know. Actually, I like the current system we have for mysql, and I voted for it back then because of my way of using ClouDB (and Alfonso also brought up the same). So basically what we do when creating a mysql database is:
- we are only really interested in the database name (giving also a user name is a bit superfluous, and also confusing a bit)
- and therefore we don't want to change every time the user name, we always use the same user name (e.g. I always use user "sorin". This way, when I connect with sorin from MYSQL workbench, I can see all my databases in one place)
- and LiferayUP is also written in such a way, as to take advantage of this framework (it creates all your databases under the same user. you can configure who that user will be, and LiferyUP will use that automatically, so you don't have to worry about that, as opposed to CloudDB UI, where we ask for so much information)

So this is why we removed the userExists check for Mysql back then. I'm not sure about the problematic use case you described now...Can we have a look at it together some time, step by step? I'm not even sure step 2 would run successfully, because of the different password we give for an existing user.

**Comment by djavorszky** [comment]
We've discussed this in person, and it makes a lot of sense to be able to use the same user for all of the databases one creates. So here's how we're going to tackle it:

1. We'll remove the option to specify a database user and password from the UI and the API
2. We'll use the creating user's authorization (e.g. part of the email) as the database user
3. We'll generate a password for the user to be used for the created databases
4. The public databases will all be created under one user and password, to be configured in the configuration file.

As an addendum, the API will have a breaking change for the create and import database endpoints, so I'll add a version to it (e.g. /api/v2/databases....).

**Comment by djavorszky** [comment]
Migrated to new location
