### ISSUE TITLE
Import fails with Access denied; you need (at least one of) the SUPER privilege(s) for this operation

### ISSUE THREAD

**Issue by sebastian-madaras** [djavorszky/ddn#278]
Hi Guys, 

If you will have time please help me with an import. I started the import and I think while validation is running the process stops with the below error message:

Importing dump failed: could not execute import command: Warning: Using a password on the command line interface can be insecure. ERROR 1227 (42000) at line 18: Access denied; you need (at least one of) the SUPER privilege(s) for this operation

If you need anything else please let me know.

Best regards,
Sebi

**Comment by sorin-pop** [comment]
After removing the following lines towards the beginning of the dump sql file:

> SET @MYSQLDUMP_TEMP_LOG_BIN = @@SESSION.SQL_LOG_BIN;
> SET @@SESSION.SQL_LOG_BIN= 0;
> 
> --
> -- GTID state at the beginning of the backup 
> --
> 
> SET @@GLOBAL.GTID_PURGED='df17de58-39bc-11e4-80b1-001517d1eadb:1-36314641';

the validation was done and the importing started to be processed.

So we assume that there is something wrong about those lines, which makes the validation of the dump file to fail.

Hope this helps, @djavorszky

**Comment by djavorszky** [comment]
Yup, that helps. We'll probably need to add a new rule for [things to remove](https://github.com/djavorszky/ddn/blob/master/agent/mysql.go#L377-L378) from the dump while validating. Let me know if you want to have a crack at it, otherwise I'll test this probably tomorrow.

**Comment by sorin-pop** [comment]
It actually turned out that this import failed as well, due to another line further down in the dump.

**Comment by sorin-pop** [comment]
I would rather leave this to you, Dani, as you are more familiar with the mysql part.

**Comment by djavorszky** [comment]
Sure, will do.

As for the other failure, should we look at it on this ticket or open a new one for it?

**Comment by sorin-pop** [comment]
As you think, I updated the comment with the second problematic line. I guess we can handle both these on this ticket.

**Comment by djavorszky** [comment]
Didn't see the update :-) Thanks. I think we can handle it on this ticket too.

**Comment by djavorszky** [comment]
I've just pushed the fix for this. Will update the agents soon.

**Comment by djavorszky** [comment]
Just deployed this, can you please test @sebastian-madaras?

**Comment by sebastian-madaras** [comment]
Hi Dani,

The improvement that you added to CloudDB has solved the import of the
original dump file.

Best regards and I appreciate the help,
Sebi
