### ISSUE TITLE
Add an Oracle 12.2 agent

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#280]
Today we received an Oracle 12.2 dump, which cannot be imported into our Oracle 12.1 agent. 12.2 is already supported in DXP, so we might slowly start getting more and more such dumps.

I don't have high hopes, but I opened a ticket with IT nevertheless: https://issues.liferay.com/browse/LRHU-1193

**Comment by djavorszky** [comment]
Any chance we could create the VM ourselves and simply hand it over to IT asking them to host it?

**Comment by sorin-pop** [comment]
I don't think we need to create it. As far as I see, there are already such VM's in files.liferay.com/private/VMs. I just used one today. I will convey this information to them to, in case they are not able to figure it out themselves.

**Comment by sorin-pop** [comment]
I am also sending a pull request related to this, Dani: https://github.com/djavorszky/ddn-agent/pull/1

The error message was quite misleading, showing only an "invalid argument value" error, from which it was not obvious what the real problem is. The real, final nested exception ("ORA-39142: incompatible version number 5.1 in dump file") has to be further digged for in the import job's error stack trace. This is what this addition does, and then it writes out also a more clear conclusion for the user, like:

" Possibly incompatible dump version (made from Oracle 12.02.00.00.00). Try importing it in a newer Oracle version. "

**Comment by djavorszky** [comment]
Awesome, thank you! Just merged it - since you only updated the import procedure, feel free to update them on the Oracle agent. There's been quite some updates with regards to configuration files (i.e. I've merged the host- and port properties for example), so if you'd like to do a "proper" update of the agent, let me know and we'll update the configuration to the new version :-)

**Comment by djavorszky** [comment]
Migrated to new location
