### ISSUE TITLE
server: uploading of huge dump file fails

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#44]
Steps:
1. Go to the Import Database page.
2. Provide a huge dump file (e.g. r2d2/tmp/sorin/test2.dmp ~ 3G).
3. Click Import.
Result: It starts uploading the file, it works on it for 10-20 seconds, then the screen below appears

![capture](https://cloud.githubusercontent.com/assets/7113037/23999859/e1a22942-0a59-11e7-8a4e-775686ec498c.PNG)

**Comment by djavorszky** [comment]
The reason for this is that the host system does not have enough disk space to handle files. Once I can write another volume we'll be able to test

**Comment by djavorszky** [comment]
This is now resolved - the server has been moved to r2d2 which has more space. That said, the connectors are still limited in their space, but that's another issue I suppose.
