### ISSUE TITLE
For Oracle, remove or grey out one of the "database name" or "user name" fields from UI

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#50]
Be aware, in the background the connector uses the user name for creating the new schema.

It would be nice to have this before go-live, because I expect it to be a little confusing for the users. But maybe I'm wrong.

**Comment by djavorszky** [comment]
Requires javascript, optimally jquery.

Proposal: onload of page and onchange of selection box: If the selected value of the dropdown contains the word "oracle", disable "database name", otherwise enable it (if disabled)

**Comment by djavorszky** [comment]
Implemented
