### ISSUE TITLE
UI: Created and Expires columns show too much (unnecessary information)

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#53]
I would argue that only the date (not even hour and minutes) would be by far sufficient for the users' needs.

I can try to do this if you want.

**Comment by djavorszky** [comment]
Yup, go ahead :)

**Comment by sorin-pop** [comment]
Hi Dani, here is the pull request: https://github.com/djavorszky/ddn/pull/64

You can accordingly modify it if you think another format would be nicer, or more user friendly. Personally I prefer words to codes and numbers, that's why I chose this format with full month name in a humanly readable word. But maybe we should use the typical hungarian date format, like 2017.03.21 (if there is such a formatting possibility in the template)? I don't know, I leave to you.

**Comment by djavorszky** [comment]
I went ahead with your suggestion, but modified it a bit: It reads as "March 22, 2017" now.

In the future, I'd like this to be configurable, so that changing it is easier.

Implemented: cd8b5875683bcd1f9a0ebb0787d2ba79788be612
