### ISSUE TITLE
Implement proper authentication

### ISSUE THREAD

**Issue by renatakovacs** [djavorszky/ddn#54]
Please connect it with LDAP. (SAML would be nice as well.)

Thanks,
Reni

**Comment by djavorszky** [comment]
Great news, this'll be easier than expected - I already have a working prototype. We just need to use github.com/jtblin/go-ldap-client.

**Comment by sorin-pop** [comment]
Migrated to https://github.com/djavorszky/liferay-support-ee/issues.
