### ISSUE TITLE
Possibility of public db-s

### ISSUE THREAD

**Issue by renatakovacs** [djavorszky/ddn#55]
Add possibility of public db-s (like FTP)

**Comment by djavorszky** [comment]
Prerequisite to this: #62 Add functionality to alter database / table

**Comment by djavorszky** [comment]
Partially (fully?) implemented as of 8db1598, though I asked @sorin-pop to double check if we're missing anything.

**Comment by djavorszky** [comment]
Implemented

**Comment by renatakovacs** [comment]
wow. thank you for the fast resolution! :)
