### ISSUE TITLE
Create "Health" component that reports the health of connectors and local database

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#56]

**Comment by djavorszky** [comment]
I believe the following could be reported:
1. Used / Free space, both absolute and percentage based
2. Size of tablespace (if applicable)
3. Currently running processes (e.g. imports) <- this in order to be able to see if the connector can be restarted or not.
4. Uptime

Other stuff we could think of reporting
1. CPU usage
2. Server load
3. io stats

What do you think @sorin-pop?

**Comment by sorin-pop** [comment]
Sure, why not? It's gonna be a lot of work though.

**Comment by djavorszky** [comment]
While at it, we could implement the same for the server as well, so we'll probably have to create a subpackage.

**Comment by djavorszky** [comment]
This is becoming more important, as we've been struggling with issues with space that was only realized due to application failure at first (everything failed due to no space left on device) and a service alert coming from Nagios.

Ideally, earlier reporting would allow us to act on the situation before it becomes critical.

**Comment by djavorszky** [comment]
And even more important: #153 

On a separate note, we need bigger disk space.
