### ISSUE TITLE
Replace placeholder kittens

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#59]

**Comment by sorin-pop** [comment]
Any news from Omar?

**Comment by djavorszky** [comment]
Nothing.. he's on vacation this week.

If you have alternative images you think would be better, do let me know (or make the update) :-)

**Comment by djavorszky** [comment]
:+1: I just received the images from Omar, switched the kittens out, now it's a billion times better :)

Implemented since 654f7af
