### ISSUE TITLE
Add API support

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#61]
Add possibility to call the server via JSON calls

**Comment by djavorszky** [comment]
Added the possibility to list the connectors (via /api/list) and to create a database (via /api/create).

I'm leaving out import - if there's a need for it, we can consider it for future releases.

Implemented as of 98ac1ae

**Comment by sorin-pop** [comment]
Hi Dani, that sounds great. Is there also some basic API documentation, examples for calling these API methods, e.g from Java code?

**Comment by djavorszky** [comment]
Hi Sorin,

No documentation yet, so just a quick not here: /api/create needs a POST request with at least two fields:
`requester_email` and `connector_identifier`. Apart from this, database name, user and password can also be specified via `dbname`, `dbuser` and `dbpass` respectively.

Upon completion, the response is a JSON struct corresponding to a DBEntry struct:
https://github.com/djavorszky/ddn/blob/master/common/model/model.go#L72

As for how this can be queried in Java or other languages, I'm not sure.. :)
