### ISSUE TITLE
Create DB input field validation missing

### ISSUE THREAD

**Issue by ZoltanTakacs** [djavorszky/ddn#68]
Write "?" in every field and push create db:

> Connector issue: creating database failed: executing create database query failed: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? CHARSET utf8' at line 1

It would be great to have a sanity check before trying to pass it to the DB server. :)

**Comment by djavorszky** [comment]
Implemented by  de8b784
