### ISSUE TITLE
server: Oracle "tablespace almost full" warning

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#70]
Implement a daily routine that checks the default tablespace (where we import the dump data) for every alive Oracle connector.

If the tablespace usage exceeds a certain (configurable) threshhold, send a warning email to the CloudDB admin. For example if it is over 90% of the tablespace max size, send email.

**Comment by djavorszky** [comment]
I think we should add this as something the connector reports when the server checks in - see #67 and #56 

Meaning, the connector should do the actual check and create a "Report" - when the server calls to see if all is well, this could be sent back with the response.

What do you think of this approach?

**Comment by sorin-pop** [comment]
Sounds good. I'll go along these lines.

**Comment by sorin-pop** [comment]
Since #154 there is no more point in checking the tablespace. Instead, we could just simply check the disk space. As this does not require specific Oracle stuff, I am unassigning myself. Dani, you probably have a much better and clearer idea on how to implement this.

**Comment by djavorszky** [comment]
You're right @sorin-pop, this is no longer necessary in the sense that the tablespace may be running out of space. We have #71, which should cover this requirement.

Thanks!
