### ISSUE TITLE
server: connector drop-down displayed names

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#74]
Shouldn't we rather display the connector short names here instead? I guess it would be more user friendly.

Unless there is some good reason for displaying the long names and this is used somewhere else and we would ruin everything switching over to shortname in connectors.html.

What do you think, Dani?

**Comment by sorin-pop** [comment]
![capture1](https://cloud.githubusercontent.com/assets/7113037/24664709/a484fcea-195b-11e7-8eac-841f37ca20da.PNG)

**Comment by djavorszky** [comment]
Originally, the idea was that there could be more than one connectors with the same short names that do differ.

We can go with the short names, however, there should be a place where end users can check more information, e.g. its version (think the actual versions of: Oracle 10.2, 11.1, 12c, etc).

Actually, now that you mention it, we should safeguard against situations where one connector could overwrite another one in the registry.

**Comment by sorin-pop** [comment]
Here is the pull request: https://github.com/djavorszky/ddn/pull/78

I think it looks better like this.

**Comment by djavorszky** [comment]
Merged, thanks! :)
