### ISSUE TITLE
Issue when uploading dump file in Windows

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#76]
I am facing this issue in my local test environment when i want to import a dump for MSSql.

Server is running locally on Windows 10.
Connector is running in a VMWare VM.

After clicking the Import button, after the file is uploaded, UI hangs, and the server logs show this error:

2017/04/06 10:35:58 [[::1]:51063]       GET     /       14.6457ms
2017/04/06 10:36:01 [[::1]:51063]       GET     /importdb       2.9289ms
2017/04/06 10:36:16 Could not removeall multipartform: remove C:\Users\LIFERA~1.E65\AppData\Local\Temp\multipart-111270531: The process cannot access the file because it is being used by another process.

I have upgraded to Go 1.8, but I am still facing this issue.

I did not encounter this issue when importing to a connector running locally for my local Oracle database.

**Comment by djavorszky** [comment]
Hi @sorin-pop ,

We found https://github.com/golang/go/issues/16296, which seemed to be a match, given how you were testing on 1.7 still. However, as you saw, upgrading to 1.8 did not solve this issue.

What seemed to do the trick was when we rebased your code to the master branch, after that, the issue seemed to have disappeared, so I'll close the ticket for now. If you do encounter it again, feel free to reopen it and we'll take a chance at resolving it.

Thanks!
