### ISSUE TITLE
Move back to bare keys in config files

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#85]
And add explanation to all of the properties. Also offer a template / default file for both the server and connector.

**Comment by djavorszky** [comment]
Implemented as of 68d26e56ec7c6acd29d847aa7d26a2630056ef13...2fccf63021ec857cb52fcfa796982b7869de4e24

@sorin-pop, @balcsida, note that you'll need to update your properties files if you have local dev environments. I've added a default configuration file for both the connector and the server with explanations on each of the properties.

**Comment by sorin-pop** [comment]
Does the Oracle connector config file need to be updated because of this? Or any other config file currently in production?

**Comment by djavorszky** [comment]
Yes, all of them.

**Comment by djavorszky** [comment]
Not yet in production though - only if the connector itself is updated in production, but we should not do that yet.
