### ISSUE TITLE
Configure agents to start up after reboot

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#90]
...because currently, if the VM is shut down and restarted for some reason (e.g IT maintenance) the connector.exe needs to be started up manually. It would be nice if it would start automatically after Windows is up (VM is on Windows).

**Comment by djavorszky** [comment]
Modified this issue, as all connectors should start up automatically after reboot:
- [ ] Oracle
- [ ] Mysql 5.5
- [ ] Mysql 5.6
- [ ] Mysql 5.7

**Comment by sorin-pop** [comment]
I did it on the Oracle VM. Although I did not test it, I'm kind of afraid to restart the VM. Should I do it?

**Comment by djavorszky** [comment]
Let's do it. You can verify the status on the web (check the status of the connector).

**Comment by sorin-pop** [comment]
Done. Oracle connector automatic restart on VM startup works.

**Comment by djavorszky** [comment]
Rest will be handled in #187
