### ISSUE TITLE
postgre import failed

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#97]
There is a failed postgres import for a public database on April 28 (made by Sebi).

We should investigate it. Dump is in r2d2/ftp/TSYSTEMSCCPUS19

**Comment by sorin-pop** [comment]
I had a look at connector/postgres.go/ImportDatabase().

Indeed, it seems that database creation is missing from it, so probably the line:

cmd := exec.Command(conf.Exec, userArg, dbreq.DatabaseName)

will fail, because the database dbreq.DatabaseName doesn't even exist at this point.

I wonder how did this pass your tests, and went live... :)

Also, I expect later we will run into the issue that I have been talking about since the beginning.

Snippet from the dump file:

`CREATE TABLE account_ (
    accountid bigint NOT NULL,
    companyid bigint,
    userid bigint,
    username character varying(75),
    createdate timestamp without time zone,
    modifieddate timestamp without time zone,
    parentaccountid bigint,
    name character varying(75),
    legalname character varying(75),
    legalid character varying(75),
    legaltype character varying(75),
    siccode character varying(75),
    tickersymbol character varying(75),
    industry character varying(75),
    type_ character varying(75),
    size_ character varying(75)
);


ALTER TABLE public.account_ OWNER TO eobr_frontend_field_test;`

In my experience, the eobr_frontend_field_test after every table creation needs to be edited to **our** target database name, otherwise all these ALTER TABLE commands will fail and the import will not be proper. Did you encounter this issue while testing, Dani?

**Comment by sorin-pop** [comment]
I can take care of all these, Dani, if you want.

**Comment by djavorszky** [comment]
Yeah, go ahead.

I think it worked for me because I was using the same database server to export the dump and also to import it - I guess, since the database already existed there, the issue didn't arise.

**Comment by djavorszky** [comment]
Issue now fixed since 83fab13062f92ad24b947a2b66a546a4ccc2aec1
