### ISSUE TITLE
Mysql server has gone away

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#98]
Steps:
1. Go to Import Database, choose Browse Server, go to _TEST folder and choose JCR_ALBATROS.sql
2. Database name: jcr_albatros (or whatever)
3. User name: sorin
4. Password: test
I used several alternatives for username and password.

Import always failed with different error messages, like:

Importing dump failed: could not execute import command: Warning: Using a password on the command line interface can be insecure.\nERROR 2006 (HY000) at line 173975: MySQL server has gone away"

"Importing dump failed: could not execute import command: ERROR 2006 (HY000) at line 57699: MySQL server has gone away"

**Comment by djavorszky** [comment]
Seems like a database configuration issue.. You were testing with mysql-56,
right?

**Comment by sorin-pop** [comment]
Yes.

**Comment by sorin-pop** [comment]
I remember having this "MySQL server has gone away" on my local server as well, with big dumps. And I think the solution was to add:

max_allowed_packet=128M

to my.ini. Just a tip.

**Comment by NorbertKocsis** [comment]
Hi,

I had the same issue.
db: 20170515-1626.dlwo_inc.sql OUNDLWO-78 account
size: 7.63 GB
connector: mysql-55 (should be 5.7 though...)
DB name: air_kit

> Import database failed
> 
> Your request to import a(n) "mysql" database named "air_kit" has failed with the following message:
> 
> "Importing dump failed: could not execute import command: ERROR 2006 (HY000) at line 11901: MySQL server has gone away"
> 
> We're sorry for the inconvenience caused.
> 
> Visit Cloud DB.

Br,
Norbert

**Comment by djavorszky** [comment]
Ok, so: afaik Norbert's dump was successfully imported to the 5.7 instance.

As for the mentioned dump, that's actually for version 5.5:
`
head JCR_ALBATROS.sql 
-- MySQL dump 10.13  Distrib 5.5.54, for Linux (x86_64)
--
-- Host: localhost    Database: JCR_ALBATROS_2017_02_01
-- ------------------------------------------------------
-- Server version	5.5.54-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

`

Still, importing to 5.5 failed as well with the same error. I'll check it soon.

**Comment by djavorszky** [comment]
I've set `max_allowed_packet=128M` in my.cnf for the 5.5 instance, however import still failed, even though our 5.5 instance is version 5.5.54 as well.

The exact message this time:
> "Importing dump failed: could not execute import command: ERROR 2006 (HY000) at line 173975: MySQL server has gone away"

Line number 173975 matches with the originally reported issue, so it's related to data. Looking into the dump, that line number corresponds to what seems like 253Mb binary data.
```
➭ awk 'FNR>=173975 && FNR<=173975' JCR_ALBATROS.sql > jcr_line 
➭ du -hs jcr_line
253M	jcr_line
```

Setting the max_allowed_packets to 260M to see if that changes anything.

**Comment by djavorszky** [comment]
Yes, that was it, import succeeded.

I'll apply this setting to all instances.

**Comment by djavorszky** [comment]
Updated all instances with a setting of `max_allowed_packets=260M`.

**Comment by NorbertKocsis** [comment]
:beer:
